# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf\ui_serverPage.ui'
#
# Created: Fri Sep 16 20:39:28 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_serverPageWidget(object):
    def setupUi(self, serverPageWidget):
        serverPageWidget.setObjectName("serverPageWidget")
        self.serverPageWidgetLayout = QtGui.QVBoxLayout(serverPageWidget)
        self.serverPageWidgetLayout.setSpacing(6)
        self.serverPageWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.serverPageWidgetLayout.setObjectName("serverPageWidgetLayout")
        self.authorizingGroupBox = QtGui.QGroupBox(serverPageWidget)
        self.authorizingGroupBox.setFlat(True)
        self.authorizingGroupBox.setObjectName("authorizingGroupBox")
        self.authorizationLayout = QtGui.QGridLayout(self.authorizingGroupBox)
        self.authorizationLayout.setSpacing(6)
        self.authorizationLayout.setContentsMargins(9, -1, 0, -1)
        self.authorizationLayout.setObjectName("authorizationLayout")
        self.userNameLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.userNameLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.authorizationLayout.addWidget(self.userNameLineEdit, 0, 1, 1, 1)
        self.userNameLable = QtGui.QLabel(self.authorizingGroupBox)
        self.userNameLable.setObjectName("userNameLable")
        self.authorizationLayout.addWidget(self.userNameLable, 0, 0, 1, 1)
        self.loginStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.loginStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.loginStatusLable.setObjectName("loginStatusLable")
        self.authorizationLayout.addWidget(self.loginStatusLable, 0, 2, 1, 1)
        self.connectToServerButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.connectToServerButton.setMinimumSize(QtCore.QSize(120, 0))
        self.connectToServerButton.setObjectName("connectToServerButton")
        self.authorizationLayout.addWidget(self.connectToServerButton, 1, 3, 1, 1)
        self.tacticStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.tacticStatusLable.setObjectName("tacticStatusLable")
        self.authorizationLayout.addWidget(self.tacticStatusLable, 1, 2, 1, 1)
        self.tacticServerLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticServerLable.setObjectName("tacticServerLable")
        self.authorizationLayout.addWidget(self.tacticServerLable, 1, 0, 1, 1)
        self.generateTicketButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.generateTicketButton.setObjectName("generateTicketButton")
        self.authorizationLayout.addWidget(self.generateTicketButton, 0, 3, 1, 1)
        self.tacticServerLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.tacticServerLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.tacticServerLineEdit.setObjectName("tacticServerLineEdit")
        self.authorizationLayout.addWidget(self.tacticServerLineEdit, 1, 1, 1, 1)
        self.savedServerPresetLabel = QtGui.QLabel(self.authorizingGroupBox)
        self.savedServerPresetLabel.setEnabled(False)
        self.savedServerPresetLabel.setObjectName("savedServerPresetLabel")
        self.authorizationLayout.addWidget(self.savedServerPresetLabel, 2, 0, 1, 1)
        self.addNewServerPresetPushButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.addNewServerPresetPushButton.setEnabled(False)
        self.addNewServerPresetPushButton.setObjectName("addNewServerPresetPushButton")
        self.authorizationLayout.addWidget(self.addNewServerPresetPushButton, 2, 3, 1, 1)
        self.serverPresetsComboBox = QtGui.QComboBox(self.authorizingGroupBox)
        self.serverPresetsComboBox.setEnabled(False)
        self.serverPresetsComboBox.setObjectName("serverPresetsComboBox")
        self.authorizationLayout.addWidget(self.serverPresetsComboBox, 2, 1, 1, 2)
        self.serverPageWidgetLayout.addWidget(self.authorizingGroupBox)
        self.environmentsGroupBox = QtGui.QGroupBox(serverPageWidget)
        self.environmentsGroupBox.setFlat(True)
        self.environmentsGroupBox.setObjectName("environmentsGroupBox")
        self.environmentLayout = QtGui.QGridLayout(self.environmentsGroupBox)
        self.environmentLayout.setSpacing(6)
        self.environmentLayout.setContentsMargins(9, -1, 0, -1)
        self.environmentLayout.setObjectName("environmentLayout")
        self.tacticEnvLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticEnvLable.setMinimumSize(QtCore.QSize(90, 0))
        self.tacticEnvLable.setObjectName("tacticEnvLable")
        self.environmentLayout.addWidget(self.tacticEnvLable, 0, 0, 1, 1)
        self.tacticEnvLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticEnvLineEdit.setObjectName("tacticEnvLineEdit")
        self.environmentLayout.addWidget(self.tacticEnvLineEdit, 0, 1, 1, 1)
        self.tacticInstallDirLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticInstallDirLable.setObjectName("tacticInstallDirLable")
        self.environmentLayout.addWidget(self.tacticInstallDirLable, 1, 0, 1, 1)
        self.tacticInstallDirLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticInstallDirLineEdit.setObjectName("tacticInstallDirLineEdit")
        self.environmentLayout.addWidget(self.tacticInstallDirLineEdit, 1, 1, 1, 1)
        self.addTacticEnv = QtGui.QPushButton(self.environmentsGroupBox)
        self.addTacticEnv.setObjectName("addTacticEnv")
        self.environmentLayout.addWidget(self.addTacticEnv, 2, 0, 1, 2)
        self.serverPageWidgetLayout.addWidget(self.environmentsGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 58, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.serverPageWidgetLayout.addItem(spacerItem)

        self.retranslateUi(serverPageWidget)
        QtCore.QMetaObject.connectSlotsByName(serverPageWidget)

    def retranslateUi(self, serverPageWidget):
        self.authorizingGroupBox.setTitle(QtGui.QApplication.translate("serverPageWidget", "Authorization:", None, QtGui.QApplication.UnicodeUTF8))
        self.userNameLable.setText(QtGui.QApplication.translate("serverPageWidget", "User Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.loginStatusLable.setText(QtGui.QApplication.translate("serverPageWidget", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectToServerButton.setText(QtGui.QApplication.translate("serverPageWidget", "Try to connect", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticStatusLable.setText(QtGui.QApplication.translate("serverPageWidget", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticServerLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic server:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateTicketButton.setText(QtGui.QApplication.translate("serverPageWidget", "Generate new Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.savedServerPresetLabel.setText(QtGui.QApplication.translate("serverPageWidget", "Server presets:", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewServerPresetPushButton.setText(QtGui.QApplication.translate("serverPageWidget", "Add new preset", None, QtGui.QApplication.UnicodeUTF8))
        self.environmentsGroupBox.setTitle(QtGui.QApplication.translate("serverPageWidget", "Tactic Environments:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticEnvLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic Data dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticInstallDirLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic Install dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.addTacticEnv.setText(QtGui.QApplication.translate("serverPageWidget", "Add Tactic environments to system", None, QtGui.QApplication.UnicodeUTF8))

