# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_conf.ui'
#
# Created: Sat Jun 11 01:39:57 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_configuration_dialog(object):
    def setupUi(self, configuration_dialog):
        configuration_dialog.setObjectName("configuration_dialog")
        configuration_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        configuration_dialog.resize(593, 693)
        configuration_dialog.setSizeGripEnabled(True)
        configuration_dialog.setModal(True)
        self.gridLayout_6 = QtGui.QGridLayout(configuration_dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.configToolBox = QtGui.QToolBox(configuration_dialog)
        self.configToolBox.setStyleSheet("QToolBox::tab {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"    padding: 3px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 25), stop: 1 rgba(175, 175, 175, 0));\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 50), stop: 1 rgba(175, 175, 175, 0));\n"
"    border: 1px solid rgba(128, 128, 128, 75);\n"
"}\n"
"QToolBox::tab:selected {\n"
"    font: italic;\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"}")
        self.configToolBox.setObjectName("configToolBox")
        self.serverPage = QtGui.QWidget()
        self.serverPage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.serverPage.setObjectName("serverPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.serverPage)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.serverOptionsLayout = QtGui.QGridLayout()
        self.serverOptionsLayout.setObjectName("serverOptionsLayout")
        self.tacticEnvLineEdit = QtGui.QLineEdit(self.serverPage)
        self.tacticEnvLineEdit.setObjectName("tacticEnvLineEdit")
        self.serverOptionsLayout.addWidget(self.tacticEnvLineEdit, 4, 1, 1, 2)
        self.tacticAssetDirLineEdit = QtGui.QLineEdit(self.serverPage)
        self.tacticAssetDirLineEdit.setObjectName("tacticAssetDirLineEdit")
        self.serverOptionsLayout.addWidget(self.tacticAssetDirLineEdit, 5, 1, 1, 2)
        self.tacticInstallDirLable = QtGui.QLabel(self.serverPage)
        self.tacticInstallDirLable.setObjectName("tacticInstallDirLable")
        self.serverOptionsLayout.addWidget(self.tacticInstallDirLable, 6, 0, 1, 1)
        self.tacticInstallDirLineEdit = QtGui.QLineEdit(self.serverPage)
        self.tacticInstallDirLineEdit.setObjectName("tacticInstallDirLineEdit")
        self.serverOptionsLayout.addWidget(self.tacticInstallDirLineEdit, 6, 1, 1, 2)
        self.tacticServerLable = QtGui.QLabel(self.serverPage)
        self.tacticServerLable.setObjectName("tacticServerLable")
        self.serverOptionsLayout.addWidget(self.tacticServerLable, 7, 0, 1, 1)
        self.tacticAssetDirLable = QtGui.QLabel(self.serverPage)
        self.tacticAssetDirLable.setObjectName("tacticAssetDirLable")
        self.serverOptionsLayout.addWidget(self.tacticAssetDirLable, 5, 0, 1, 1)
        self.tacticEnvLable = QtGui.QLabel(self.serverPage)
        self.tacticEnvLable.setObjectName("tacticEnvLable")
        self.serverOptionsLayout.addWidget(self.tacticEnvLable, 4, 0, 1, 1)
        self.generateTicketButton = QtGui.QPushButton(self.serverPage)
        self.generateTicketButton.setObjectName("generateTicketButton")
        self.serverOptionsLayout.addWidget(self.generateTicketButton, 2, 1, 1, 2)
        self.loginStatusLable = QtGui.QLabel(self.serverPage)
        self.loginStatusLable.setObjectName("loginStatusLable")
        self.serverOptionsLayout.addWidget(self.loginStatusLable, 2, 0, 1, 1)
        self.userNameLineEdit = QtGui.QLineEdit(self.serverPage)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.serverOptionsLayout.addWidget(self.userNameLineEdit, 0, 1, 1, 2)
        self.tacticServerLineEdit = QtGui.QLineEdit(self.serverPage)
        self.tacticServerLineEdit.setObjectName("tacticServerLineEdit")
        self.serverOptionsLayout.addWidget(self.tacticServerLineEdit, 7, 1, 1, 2)
        self.passwordLineEdit = QtGui.QLineEdit(self.serverPage)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.serverOptionsLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 2)
        self.passwordLable = QtGui.QLabel(self.serverPage)
        self.passwordLable.setObjectName("passwordLable")
        self.serverOptionsLayout.addWidget(self.passwordLable, 1, 0, 1, 1)
        self.userNameLable = QtGui.QLabel(self.serverPage)
        self.userNameLable.setObjectName("userNameLable")
        self.serverOptionsLayout.addWidget(self.userNameLable, 0, 0, 1, 1)
        self.tacticStatusLable = QtGui.QLabel(self.serverPage)
        self.tacticStatusLable.setObjectName("tacticStatusLable")
        self.serverOptionsLayout.addWidget(self.tacticStatusLable, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.serverOptionsLayout.addItem(spacerItem, 9, 2, 1, 1)
        self.connectToServerButton = QtGui.QPushButton(self.serverPage)
        self.connectToServerButton.setMinimumSize(QtCore.QSize(120, 0))
        self.connectToServerButton.setObjectName("connectToServerButton")
        self.serverOptionsLayout.addWidget(self.connectToServerButton, 8, 1, 1, 1)
        self.addTacticEnv = QtGui.QPushButton(self.serverPage)
        self.addTacticEnv.setObjectName("addTacticEnv")
        self.serverOptionsLayout.addWidget(self.addTacticEnv, 8, 2, 1, 1)
        self.serverOptionsLayout.setColumnStretch(2, 1)
        self.verticalLayout_2.addLayout(self.serverOptionsLayout)
        self.configToolBox.addItem(self.serverPage, "")
        self.projectPage = QtGui.QWidget()
        self.projectPage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.projectPage.setObjectName("projectPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.projectPage)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.templateProjectsLabel = QtGui.QLabel(self.projectPage)
        self.templateProjectsLabel.setStyleSheet("QLabel {background :rgb(50, 150, 175)}")
        self.templateProjectsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.templateProjectsLabel.setObjectName("templateProjectsLabel")
        self.gridLayout.addWidget(self.templateProjectsLabel, 1, 5, 1, 1)
        self.colorSchemeHintLabel = QtGui.QLabel(self.projectPage)
        self.colorSchemeHintLabel.setObjectName("colorSchemeHintLabel")
        self.gridLayout.addWidget(self.colorSchemeHintLabel, 1, 3, 1, 1)
        self.createProjectsLable = QtGui.QLabel(self.projectPage)
        self.createProjectsLable.setObjectName("createProjectsLable")
        self.gridLayout.addWidget(self.createProjectsLable, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.createProjectPushButton = QtGui.QPushButton(self.projectPage)
        self.createProjectPushButton.setObjectName("createProjectPushButton")
        self.gridLayout.addWidget(self.createProjectPushButton, 1, 1, 1, 1)
        self.projectsTreeWidget = QtGui.QTreeWidget(self.projectPage)
        self.projectsTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.projectsTreeWidget.setObjectName("projectsTreeWidget")
        self.projectsTreeWidget.header().setDefaultSectionSize(87)
        self.gridLayout.addWidget(self.projectsTreeWidget, 0, 0, 1, 6)
        self.currentProjectLabel = QtGui.QLabel(self.projectPage)
        self.currentProjectLabel.setStyleSheet("QLabel {background : rgb(165, 175, 25);}")
        self.currentProjectLabel.setTextFormat(QtCore.Qt.PlainText)
        self.currentProjectLabel.setObjectName("currentProjectLabel")
        self.gridLayout.addWidget(self.currentProjectLabel, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.configToolBox.addItem(self.projectPage, "")
        self.checkoutPage = QtGui.QWidget()
        self.checkoutPage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.checkoutPage.setObjectName("checkoutPage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.checkoutPage)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkoutMiscOpitionsGroupBox = QtGui.QGroupBox(self.checkoutPage)
        self.checkoutMiscOpitionsGroupBox.setFlat(True)
        self.checkoutMiscOpitionsGroupBox.setObjectName("checkoutMiscOpitionsGroupBox")
        self.checkoutMiscOptionsLayout = QtGui.QGridLayout(self.checkoutMiscOpitionsGroupBox)
        self.checkoutMiscOptionsLayout.setContentsMargins(0, -1, 0, 0)
        self.checkoutMiscOptionsLayout.setObjectName("checkoutMiscOptionsLayout")
        self.doubleClickOpenCheckBox = QtGui.QCheckBox(self.checkoutMiscOpitionsGroupBox)
        self.doubleClickOpenCheckBox.setObjectName("doubleClickOpenCheckBox")
        self.checkoutMiscOptionsLayout.addWidget(self.doubleClickOpenCheckBox, 0, 0, 1, 1)
        self.versionsSeparateCheckoutCheckBox = QtGui.QCheckBox(self.checkoutMiscOpitionsGroupBox)
        self.versionsSeparateCheckoutCheckBox.setObjectName("versionsSeparateCheckoutCheckBox")
        self.checkoutMiscOptionsLayout.addWidget(self.versionsSeparateCheckoutCheckBox, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.checkoutMiscOpitionsGroupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.configToolBox.addItem(self.checkoutPage, "")
        self.checkinPage = QtGui.QWidget()
        self.checkinPage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.checkinPage.setObjectName("checkinPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.checkinPage)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkinPageLayout = QtGui.QGridLayout()
        self.checkinPageLayout.setObjectName("checkinPageLayout")
        self.customRepoPathsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.customRepoPathsGroupBox.setFlat(True)
        self.customRepoPathsGroupBox.setObjectName("customRepoPathsGroupBox")
        self.customRepoPathsLayout = QtGui.QGridLayout(self.customRepoPathsGroupBox)
        self.customRepoPathsLayout.setContentsMargins(0, -1, 0, 0)
        self.customRepoPathsLayout.setObjectName("customRepoPathsLayout")
        self.customRepoCheckBox = QtGui.QCheckBox(self.customRepoPathsGroupBox)
        self.customRepoCheckBox.setObjectName("customRepoCheckBox")
        self.customRepoPathsLayout.addWidget(self.customRepoCheckBox, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_7.setObjectName("label_7")
        self.customRepoPathsLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.customRepoDirNameLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirNameLineEdit.setObjectName("customRepoDirNameLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirNameLineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_8.setObjectName("label_8")
        self.customRepoPathsLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.customRepoDirPathLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirPathLineEdit.setObjectName("customRepoDirPathLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirPathLineEdit, 1, 3, 1, 3)
        self.addCustomRepoToListPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.addCustomRepoToListPushButton.setObjectName("addCustomRepoToListPushButton")
        self.customRepoPathsLayout.addWidget(self.addCustomRepoToListPushButton, 1, 6, 1, 1)
        self.customRepoTreeWidget = QtGui.QTreeWidget(self.customRepoPathsGroupBox)
        self.customRepoTreeWidget.setIndentation(0)
        self.customRepoTreeWidget.setRootIsDecorated(False)
        self.customRepoTreeWidget.setObjectName("customRepoTreeWidget")
        self.customRepoPathsLayout.addWidget(self.customRepoTreeWidget, 2, 0, 1, 7)
        self.deleteCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.deleteCustomRepoPushButton.setObjectName("deleteCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.deleteCustomRepoPushButton, 0, 6, 1, 1)
        self.editCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.editCustomRepoPushButton.setObjectName("editCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.editCustomRepoPushButton, 0, 5, 1, 1)
        self.customRepoComboBox = QtGui.QComboBox(self.customRepoPathsGroupBox)
        self.customRepoComboBox.setObjectName("customRepoComboBox")
        self.customRepoPathsLayout.addWidget(self.customRepoComboBox, 0, 1, 1, 4)
        self.checkinPageLayout.addWidget(self.customRepoPathsGroupBox, 0, 0, 1, 1)
        self.checkinMiscOpitionsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.checkinMiscOpitionsGroupBox.setFlat(True)
        self.checkinMiscOpitionsGroupBox.setObjectName("checkinMiscOpitionsGroupBox")
        self.checkinMiscOptionsLayout = QtGui.QGridLayout(self.checkinMiscOpitionsGroupBox)
        self.checkinMiscOptionsLayout.setContentsMargins(0, -1, 0, 0)
        self.checkinMiscOptionsLayout.setObjectName("checkinMiscOptionsLayout")
        self.doubleClickSaveCheckBox = QtGui.QCheckBox(self.checkinMiscOpitionsGroupBox)
        self.doubleClickSaveCheckBox.setObjectName("doubleClickSaveCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.doubleClickSaveCheckBox, 0, 0, 1, 1)
        self.versionsSeparateCheckinCheckBox = QtGui.QCheckBox(self.checkinMiscOpitionsGroupBox)
        self.versionsSeparateCheckinCheckBox.setObjectName("versionsSeparateCheckinCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.versionsSeparateCheckinCheckBox, 1, 0, 1, 1)
        self.checkinPageLayout.addWidget(self.checkinMiscOpitionsGroupBox, 2, 0, 1, 1)
        self.defaultRepoPathsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.defaultRepoPathsGroupBox.setFlat(True)
        self.defaultRepoPathsGroupBox.setObjectName("defaultRepoPathsGroupBox")
        self.defaultRepoPathsLayout = QtGui.QGridLayout(self.defaultRepoPathsGroupBox)
        self.defaultRepoPathsLayout.setSpacing(6)
        self.defaultRepoPathsLayout.setContentsMargins(0, 9, 0, 0)
        self.defaultRepoPathsLayout.setObjectName("defaultRepoPathsLayout")
        self.assetBaseDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirPathLineEdit.setObjectName("assetBaseDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirPathLineEdit, 0, 2, 1, 1)
        self.handoffDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.handoffDirPathLineEdit.setObjectName("handoffDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.handoffDirPathLineEdit, 4, 1, 1, 2)
        self.sandboxDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirPathLineEdit.setObjectName("sandboxDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirPathLineEdit, 1, 2, 1, 1)
        self.localRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirPathLineEdit.setObjectName("localRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirPathLineEdit, 2, 2, 1, 1)
        self.clientRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirPathLineEdit.setObjectName("clientRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirPathLineEdit, 3, 2, 1, 1)
        self.assetBaseDirCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.assetBaseDirCheckBox.setChecked(True)
        self.assetBaseDirCheckBox.setObjectName("assetBaseDirCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirCheckBox, 0, 0, 1, 1)
        self.sandboxCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.sandboxCheckBox.setObjectName("sandboxCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.sandboxCheckBox, 1, 0, 1, 1)
        self.localRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.localRepoCheckBox.setChecked(True)
        self.localRepoCheckBox.setObjectName("localRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.localRepoCheckBox, 2, 0, 1, 1)
        self.clientRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.clientRepoCheckBox.setObjectName("clientRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoCheckBox, 3, 0, 1, 1)
        self.handoffCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.handoffCheckBox.setObjectName("handoffCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.handoffCheckBox, 4, 0, 1, 1)
        self.assetBaseDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirNameLineEdit.setObjectName("assetBaseDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirNameLineEdit, 0, 1, 1, 1)
        self.sandboxDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirNameLineEdit.setObjectName("sandboxDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirNameLineEdit, 1, 1, 1, 1)
        self.localRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirNameLineEdit.setObjectName("localRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirNameLineEdit, 2, 1, 1, 1)
        self.clientRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirNameLineEdit.setObjectName("clientRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirNameLineEdit, 3, 1, 1, 1)
        self.defaultRepoPathsLayout.setColumnStretch(2, 1)
        self.checkinPageLayout.addWidget(self.defaultRepoPathsGroupBox, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.checkinPageLayout)
        self.configToolBox.addItem(self.checkinPage, "")
        self.checkinOutPage = QtGui.QWidget()
        self.checkinOutPage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.checkinOutPage.setObjectName("checkinOutPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.checkinOutPage)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.processTreeWidget = QtGui.QTreeWidget(self.checkinOutPage)
        self.processTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.processTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.processTreeWidget.setObjectName("processTreeWidget")
        self.processTreeWidget.header().setDefaultSectionSize(240)
        self.processTreeWidget.header().setMinimumSectionSize(170)
        self.gridLayout_4.addWidget(self.processTreeWidget, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.configToolBox.addItem(self.checkinOutPage, "")
        self.scenePage = QtGui.QWidget()
        self.scenePage.setGeometry(QtCore.QRect(0, 0, 575, 484))
        self.scenePage.setObjectName("scenePage")
        self.verticalLayout = QtGui.QVBoxLayout(self.scenePage)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.currentWorkdirLable = QtGui.QLabel(self.scenePage)
        self.currentWorkdirLable.setObjectName("currentWorkdirLable")
        self.gridLayout_2.addWidget(self.currentWorkdirLable, 0, 0, 1, 1)
        self.currentWorkdirLineEdit = QtGui.QLineEdit(self.scenePage)
        self.currentWorkdirLineEdit.setReadOnly(True)
        self.currentWorkdirLineEdit.setObjectName("currentWorkdirLineEdit")
        self.gridLayout_2.addWidget(self.currentWorkdirLineEdit, 0, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 100)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.configToolBox.addItem(self.scenePage, "")
        self.gridLayout_6.addWidget(self.configToolBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(configuration_dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(configuration_dialog)
        self.configToolBox.setCurrentIndex(0)
        self.configToolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(configuration_dialog)
        configuration_dialog.setTabOrder(self.userNameLineEdit, self.passwordLineEdit)
        configuration_dialog.setTabOrder(self.passwordLineEdit, self.generateTicketButton)
        configuration_dialog.setTabOrder(self.generateTicketButton, self.tacticEnvLineEdit)
        configuration_dialog.setTabOrder(self.tacticEnvLineEdit, self.tacticAssetDirLineEdit)
        configuration_dialog.setTabOrder(self.tacticAssetDirLineEdit, self.tacticInstallDirLineEdit)
        configuration_dialog.setTabOrder(self.tacticInstallDirLineEdit, self.buttonBox)
        configuration_dialog.setTabOrder(self.buttonBox, self.currentWorkdirLineEdit)

    def retranslateUi(self, configuration_dialog):
        configuration_dialog.setWindowTitle(QtGui.QApplication.translate("configuration_dialog", "TACTIC Handler configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticInstallDirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic Install dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticServerLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic server:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticAssetDirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic assets dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticEnvLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic database:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateTicketButton.setText(QtGui.QApplication.translate("configuration_dialog", "Generate new Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.loginStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLable.setText(QtGui.QApplication.translate("configuration_dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.userNameLable.setText(QtGui.QApplication.translate("configuration_dialog", "User Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectToServerButton.setText(QtGui.QApplication.translate("configuration_dialog", "Try to connect", None, QtGui.QApplication.UnicodeUTF8))
        self.addTacticEnv.setText(QtGui.QApplication.translate("configuration_dialog", "Add Tactic environments to system", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.serverPage), QtGui.QApplication.translate("configuration_dialog", "TACTIC Server", None, QtGui.QApplication.UnicodeUTF8))
        self.templateProjectsLabel.setText(QtGui.QApplication.translate("configuration_dialog", " Template Projects ", None, QtGui.QApplication.UnicodeUTF8))
        self.colorSchemeHintLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Scheme: ", None, QtGui.QApplication.UnicodeUTF8))
        self.createProjectsLable.setText(QtGui.QApplication.translate("configuration_dialog", "Create new Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.createProjectPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.setToolTip(QtGui.QApplication.translate("configuration_dialog", "Right click for menu", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.setStatusTip(QtGui.QApplication.translate("configuration_dialog", "Right click for menu", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Category/Title", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("configuration_dialog", "Namespace (template)", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("configuration_dialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.currentProjectLabel.setText(QtGui.QApplication.translate("configuration_dialog", " Current Project ", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.projectPage), QtGui.QApplication.translate("configuration_dialog", "Project (restart required to apply)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkoutMiscOpitionsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickOpenCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "DoubleClick for Open", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsSeparateCheckoutCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Display versions separate", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkoutPage), QtGui.QApplication.translate("configuration_dialog", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Custom repository path:", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Show custom repos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("configuration_dialog", "Repo name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("configuration_dialog", "Repo path:", None, QtGui.QApplication.UnicodeUTF8))
        self.addCustomRepoToListPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Custom repo name", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("configuration_dialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCustomRepoPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.editCustomRepoPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMiscOpitionsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickSaveCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "DoubleClick for Save", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsSeparateCheckinCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Display versions separate", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Current repository paths:", None, QtGui.QApplication.UnicodeUTF8))
        self.assetBaseDirCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Asset base dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.sandboxCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Sandbox dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.localRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Local repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Client repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.handoffCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Handoff dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkinPage), QtGui.QApplication.translate("configuration_dialog", "Checkin", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Category/Title", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkinOutPage), QtGui.QApplication.translate("configuration_dialog", "Checkin/Checkout display (for current Project and environment)", None, QtGui.QApplication.UnicodeUTF8))
        self.currentWorkdirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Current Workdir:", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.scenePage), QtGui.QApplication.translate("configuration_dialog", "Maya Scene", None, QtGui.QApplication.UnicodeUTF8))

