# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_conf.ui'
#
# Created: Sun Jul 10 23:19:48 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_configuration_dialog(object):
    def setupUi(self, configuration_dialog):
        configuration_dialog.setObjectName("configuration_dialog")
        configuration_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        configuration_dialog.resize(482, 744)
        configuration_dialog.setSizeGripEnabled(True)
        configuration_dialog.setModal(True)
        self.gridLayout_6 = QtGui.QGridLayout(configuration_dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.buttonBox = QtGui.QDialogButtonBox(configuration_dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.configToolBox = QtGui.QToolBox(configuration_dialog)
        self.configToolBox.setStyleSheet("QToolBox::tab {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"    padding: 3px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 25), stop: 1 rgba(175, 175, 175, 0));\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 50), stop: 1 rgba(175, 175, 175, 0));\n"
"    border: 1px solid rgba(128, 128, 128, 75);\n"
"}\n"
"QToolBox::tab:selected {\n"
"    font: italic;\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"}")
        self.configToolBox.setObjectName("configToolBox")
        self.serverPage = QtGui.QWidget()
        self.serverPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.serverPage.setObjectName("serverPage")
        self.serverOptionsLayout = QtGui.QGridLayout(self.serverPage)
        self.serverOptionsLayout.setContentsMargins(6, 6, 6, 6)
        self.serverOptionsLayout.setObjectName("serverOptionsLayout")
        self.environmentsGroupBox = QtGui.QGroupBox(self.serverPage)
        self.environmentsGroupBox.setFlat(True)
        self.environmentsGroupBox.setObjectName("environmentsGroupBox")
        self.environmentLayout = QtGui.QGridLayout(self.environmentsGroupBox)
        self.environmentLayout.setContentsMargins(0, -1, 0, 0)
        self.environmentLayout.setObjectName("environmentLayout")
        self.tacticEnvLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticEnvLable.setMinimumSize(QtCore.QSize(90, 0))
        self.tacticEnvLable.setObjectName("tacticEnvLable")
        self.environmentLayout.addWidget(self.tacticEnvLable, 0, 0, 1, 1)
        self.tacticEnvLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticEnvLineEdit.setObjectName("tacticEnvLineEdit")
        self.environmentLayout.addWidget(self.tacticEnvLineEdit, 0, 1, 1, 1)
        self.tacticInstallDirLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticInstallDirLable.setObjectName("tacticInstallDirLable")
        self.environmentLayout.addWidget(self.tacticInstallDirLable, 1, 0, 1, 1)
        self.tacticInstallDirLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticInstallDirLineEdit.setObjectName("tacticInstallDirLineEdit")
        self.environmentLayout.addWidget(self.tacticInstallDirLineEdit, 1, 1, 1, 1)
        self.addTacticEnv = QtGui.QPushButton(self.environmentsGroupBox)
        self.addTacticEnv.setObjectName("addTacticEnv")
        self.environmentLayout.addWidget(self.addTacticEnv, 3, 0, 1, 2)
        self.serverOptionsLayout.addWidget(self.environmentsGroupBox, 1, 0, 1, 1)
        self.authorizingGroupBox = QtGui.QGroupBox(self.serverPage)
        self.authorizingGroupBox.setFlat(True)
        self.authorizingGroupBox.setObjectName("authorizingGroupBox")
        self.authorizationLayout = QtGui.QGridLayout(self.authorizingGroupBox)
        self.authorizationLayout.setContentsMargins(0, -1, 0, 0)
        self.authorizationLayout.setObjectName("authorizationLayout")
        self.connectToServerButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.connectToServerButton.setMinimumSize(QtCore.QSize(120, 0))
        self.connectToServerButton.setObjectName("connectToServerButton")
        self.authorizationLayout.addWidget(self.connectToServerButton, 4, 3, 1, 1)
        self.userNameLable = QtGui.QLabel(self.authorizingGroupBox)
        self.userNameLable.setObjectName("userNameLable")
        self.authorizationLayout.addWidget(self.userNameLable, 0, 0, 1, 1)
        self.userNameLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.authorizationLayout.addWidget(self.userNameLineEdit, 0, 1, 1, 3)
        self.passwordLable = QtGui.QLabel(self.authorizingGroupBox)
        self.passwordLable.setObjectName("passwordLable")
        self.authorizationLayout.addWidget(self.passwordLable, 1, 0, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.authorizationLayout.addWidget(self.passwordLineEdit, 1, 1, 1, 3)
        self.loginStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.loginStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.loginStatusLable.setObjectName("loginStatusLable")
        self.authorizationLayout.addWidget(self.loginStatusLable, 4, 0, 1, 1)
        self.generateTicketButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.generateTicketButton.setObjectName("generateTicketButton")
        self.authorizationLayout.addWidget(self.generateTicketButton, 4, 1, 1, 1)
        self.tacticStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.tacticStatusLable.setObjectName("tacticStatusLable")
        self.authorizationLayout.addWidget(self.tacticStatusLable, 4, 2, 1, 1)
        self.tacticServerLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticServerLable.setObjectName("tacticServerLable")
        self.authorizationLayout.addWidget(self.tacticServerLable, 2, 0, 1, 1)
        self.tacticServerLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.tacticServerLineEdit.setObjectName("tacticServerLineEdit")
        self.authorizationLayout.addWidget(self.tacticServerLineEdit, 2, 1, 1, 3)
        self.authorizationLayout.setColumnStretch(1, 1)
        self.authorizationLayout.setColumnStretch(3, 1)
        self.serverOptionsLayout.addWidget(self.authorizingGroupBox, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.serverOptionsLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.configToolBox.addItem(self.serverPage, "")
        self.projectPage = QtGui.QWidget()
        self.projectPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.projectPage.setObjectName("projectPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.projectPage)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.templateProjectsLabel = QtGui.QLabel(self.projectPage)
        self.templateProjectsLabel.setStyleSheet("QLabel {background :rgb(50, 150, 175)}")
        self.templateProjectsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.templateProjectsLabel.setObjectName("templateProjectsLabel")
        self.gridLayout.addWidget(self.templateProjectsLabel, 1, 5, 1, 1)
        self.colorSchemeHintLabel = QtGui.QLabel(self.projectPage)
        self.colorSchemeHintLabel.setObjectName("colorSchemeHintLabel")
        self.gridLayout.addWidget(self.colorSchemeHintLabel, 1, 3, 1, 1)
        self.createProjectsLable = QtGui.QLabel(self.projectPage)
        self.createProjectsLable.setObjectName("createProjectsLable")
        self.gridLayout.addWidget(self.createProjectsLable, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.createProjectPushButton = QtGui.QPushButton(self.projectPage)
        self.createProjectPushButton.setObjectName("createProjectPushButton")
        self.gridLayout.addWidget(self.createProjectPushButton, 1, 1, 1, 1)
        self.projectsTreeWidget = QtGui.QTreeWidget(self.projectPage)
        self.projectsTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.projectsTreeWidget.setObjectName("projectsTreeWidget")
        self.projectsTreeWidget.header().setDefaultSectionSize(87)
        self.gridLayout.addWidget(self.projectsTreeWidget, 0, 0, 1, 6)
        self.currentProjectLabel = QtGui.QLabel(self.projectPage)
        self.currentProjectLabel.setStyleSheet("QLabel {background : rgb(165, 175, 25);}")
        self.currentProjectLabel.setTextFormat(QtCore.Qt.PlainText)
        self.currentProjectLabel.setObjectName("currentProjectLabel")
        self.gridLayout.addWidget(self.currentProjectLabel, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.configToolBox.addItem(self.projectPage, "")
        self.checkoutPage = QtGui.QWidget()
        self.checkoutPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.checkoutPage.setObjectName("checkoutPage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.checkoutPage)
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkoutMiscOpitionsGroupBox = QtGui.QGroupBox(self.checkoutPage)
        self.checkoutMiscOpitionsGroupBox.setFlat(True)
        self.checkoutMiscOpitionsGroupBox.setObjectName("checkoutMiscOpitionsGroupBox")
        self.checkoutMiscOptionsLayout = QtGui.QGridLayout(self.checkoutMiscOpitionsGroupBox)
        self.checkoutMiscOptionsLayout.setContentsMargins(0, -1, 0, 0)
        self.checkoutMiscOptionsLayout.setObjectName("checkoutMiscOptionsLayout")
        self.doubleClickOpenCheckBox = QtGui.QCheckBox(self.checkoutMiscOpitionsGroupBox)
        self.doubleClickOpenCheckBox.setObjectName("doubleClickOpenCheckBox")
        self.checkoutMiscOptionsLayout.addWidget(self.doubleClickOpenCheckBox, 0, 0, 1, 1)
        self.versionsSeparateCheckoutCheckBox = QtGui.QCheckBox(self.checkoutMiscOpitionsGroupBox)
        self.versionsSeparateCheckoutCheckBox.setObjectName("versionsSeparateCheckoutCheckBox")
        self.checkoutMiscOptionsLayout.addWidget(self.versionsSeparateCheckoutCheckBox, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.checkoutMiscOpitionsGroupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.configToolBox.addItem(self.checkoutPage, "")
        self.checkinPage = QtGui.QWidget()
        self.checkinPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.checkinPage.setObjectName("checkinPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.checkinPage)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkinPageLayout = QtGui.QGridLayout()
        self.checkinPageLayout.setObjectName("checkinPageLayout")
        self.checkinMiscOpitionsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.checkinMiscOpitionsGroupBox.setFlat(True)
        self.checkinMiscOpitionsGroupBox.setObjectName("checkinMiscOpitionsGroupBox")
        self.checkinMiscOptionsLayout = QtGui.QGridLayout(self.checkinMiscOpitionsGroupBox)
        self.checkinMiscOptionsLayout.setContentsMargins(0, -1, 0, 0)
        self.checkinMiscOptionsLayout.setObjectName("checkinMiscOptionsLayout")
        self.doubleClickSaveCheckBox = QtGui.QCheckBox(self.checkinMiscOpitionsGroupBox)
        self.doubleClickSaveCheckBox.setObjectName("doubleClickSaveCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.doubleClickSaveCheckBox, 0, 0, 1, 1)
        self.versionsSeparateCheckinCheckBox = QtGui.QCheckBox(self.checkinMiscOpitionsGroupBox)
        self.versionsSeparateCheckinCheckBox.setObjectName("versionsSeparateCheckinCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.versionsSeparateCheckinCheckBox, 1, 0, 1, 1)
        self.checkinPageLayout.addWidget(self.checkinMiscOpitionsGroupBox, 2, 0, 1, 1)
        self.defaultRepoPathsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.defaultRepoPathsGroupBox.setFlat(True)
        self.defaultRepoPathsGroupBox.setObjectName("defaultRepoPathsGroupBox")
        self.defaultRepoPathsLayout = QtGui.QGridLayout(self.defaultRepoPathsGroupBox)
        self.defaultRepoPathsLayout.setSpacing(6)
        self.defaultRepoPathsLayout.setContentsMargins(0, 9, 0, 0)
        self.defaultRepoPathsLayout.setObjectName("defaultRepoPathsLayout")
        self.assetBaseDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirPathLineEdit.setObjectName("assetBaseDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirPathLineEdit, 0, 3, 1, 1)
        self.handoffDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.handoffDirPathLineEdit.setObjectName("handoffDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.handoffDirPathLineEdit, 4, 2, 1, 2)
        self.sandboxDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirPathLineEdit.setObjectName("sandboxDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirPathLineEdit, 1, 3, 1, 1)
        self.localRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirPathLineEdit.setObjectName("localRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirPathLineEdit, 2, 3, 1, 1)
        self.clientRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirPathLineEdit.setObjectName("clientRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirPathLineEdit, 3, 3, 1, 1)
        self.assetBaseDirCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.assetBaseDirCheckBox.setChecked(True)
        self.assetBaseDirCheckBox.setObjectName("assetBaseDirCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirCheckBox, 0, 0, 1, 1)
        self.sandboxCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.sandboxCheckBox.setObjectName("sandboxCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.sandboxCheckBox, 1, 0, 1, 1)
        self.localRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.localRepoCheckBox.setChecked(True)
        self.localRepoCheckBox.setObjectName("localRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.localRepoCheckBox, 2, 0, 1, 1)
        self.clientRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.clientRepoCheckBox.setObjectName("clientRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoCheckBox, 3, 0, 1, 1)
        self.handoffCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.handoffCheckBox.setObjectName("handoffCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.handoffCheckBox, 4, 0, 1, 1)
        self.assetBaseDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirNameLineEdit.setObjectName("assetBaseDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirNameLineEdit, 0, 2, 1, 1)
        self.sandboxDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirNameLineEdit.setObjectName("sandboxDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirNameLineEdit, 1, 2, 1, 1)
        self.localRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirNameLineEdit.setObjectName("localRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirNameLineEdit, 2, 2, 1, 1)
        self.clientRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirNameLineEdit.setObjectName("clientRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirNameLineEdit, 3, 2, 1, 1)
        self.assetBaseDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.assetBaseDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.assetBaseDirColorToolButton.setStyleSheet("background-color:rgb(64, 64, 64)")
        self.assetBaseDirColorToolButton.setChecked(False)
        self.assetBaseDirColorToolButton.setObjectName("assetBaseDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirColorToolButton, 0, 1, 1, 1)
        self.sandboxDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.sandboxDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.sandboxDirColorToolButton.setStyleSheet("background-color:rgb(128, 64, 64)")
        self.sandboxDirColorToolButton.setChecked(False)
        self.sandboxDirColorToolButton.setObjectName("sandboxDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirColorToolButton, 1, 1, 1, 1)
        self.localRepoDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.localRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.localRepoDirColorToolButton.setStyleSheet("background-color:rgb(255, 140, 40)")
        self.localRepoDirColorToolButton.setChecked(False)
        self.localRepoDirColorToolButton.setObjectName("localRepoDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirColorToolButton, 2, 1, 1, 1)
        self.clientRepoDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.clientRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.clientRepoDirColorToolButton.setStyleSheet("background-color:rgb(31, 143, 0)")
        self.clientRepoDirColorToolButton.setChecked(False)
        self.clientRepoDirColorToolButton.setObjectName("clientRepoDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirColorToolButton, 3, 1, 1, 1)
        self.checkinPageLayout.addWidget(self.defaultRepoPathsGroupBox, 1, 0, 1, 1)
        self.customRepoPathsGroupBox = QtGui.QGroupBox(self.checkinPage)
        self.customRepoPathsGroupBox.setFlat(True)
        self.customRepoPathsGroupBox.setObjectName("customRepoPathsGroupBox")
        self.customRepoPathsLayout = QtGui.QGridLayout(self.customRepoPathsGroupBox)
        self.customRepoPathsLayout.setSpacing(6)
        self.customRepoPathsLayout.setContentsMargins(0, -1, 0, -1)
        self.customRepoPathsLayout.setObjectName("customRepoPathsLayout")
        self.label_7 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_7.setObjectName("label_7")
        self.customRepoPathsLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.customRepoDirColorToolButton = QtGui.QToolButton(self.customRepoPathsGroupBox)
        self.customRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.customRepoDirColorToolButton.setStyleSheet("background-color:rgb(64, 64, 64)")
        self.customRepoDirColorToolButton.setChecked(False)
        self.customRepoDirColorToolButton.setObjectName("customRepoDirColorToolButton")
        self.customRepoPathsLayout.addWidget(self.customRepoDirColorToolButton, 0, 1, 1, 1)
        self.customRepoDirNameLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirNameLineEdit.setObjectName("customRepoDirNameLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirNameLineEdit, 0, 2, 1, 3)
        self.label_8 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_8.setObjectName("label_8")
        self.customRepoPathsLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.customRepoDirPathLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirPathLineEdit.setObjectName("customRepoDirPathLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirPathLineEdit, 1, 1, 1, 4)
        self.customRepoComboBox = QtGui.QComboBox(self.customRepoPathsGroupBox)
        self.customRepoComboBox.setObjectName("customRepoComboBox")
        self.customRepoPathsLayout.addWidget(self.customRepoComboBox, 2, 0, 1, 1)
        self.addCustomRepoToListPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.addCustomRepoToListPushButton.setObjectName("addCustomRepoToListPushButton")
        self.customRepoPathsLayout.addWidget(self.addCustomRepoToListPushButton, 2, 1, 1, 2)
        self.editCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.editCustomRepoPushButton.setObjectName("editCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.editCustomRepoPushButton, 2, 3, 1, 1)
        self.deleteCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.deleteCustomRepoPushButton.setObjectName("deleteCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.deleteCustomRepoPushButton, 2, 4, 1, 1)
        self.customRepoCheckBox = QtGui.QCheckBox(self.customRepoPathsGroupBox)
        self.customRepoCheckBox.setObjectName("customRepoCheckBox")
        self.customRepoPathsLayout.addWidget(self.customRepoCheckBox, 3, 0, 1, 1)
        self.customRepoTreeWidget = QtGui.QTreeWidget(self.customRepoPathsGroupBox)
        self.customRepoTreeWidget.setIndentation(0)
        self.customRepoTreeWidget.setRootIsDecorated(False)
        self.customRepoTreeWidget.setObjectName("customRepoTreeWidget")
        self.customRepoPathsLayout.addWidget(self.customRepoTreeWidget, 4, 0, 1, 5)
        self.checkinPageLayout.addWidget(self.customRepoPathsGroupBox, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.checkinPageLayout)
        self.configToolBox.addItem(self.checkinPage, "")
        self.checkinOutPage = QtGui.QWidget()
        self.checkinOutPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.checkinOutPage.setObjectName("checkinOutPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.checkinOutPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.snapshotDisplayOptionsGroupBox = QtGui.QGroupBox(self.checkinOutPage)
        self.snapshotDisplayOptionsGroupBox.setFlat(True)
        self.snapshotDisplayOptionsGroupBox.setObjectName("snapshotDisplayOptionsGroupBox")
        self.snapshotDisplayOptionsLayout = QtGui.QHBoxLayout(self.snapshotDisplayOptionsGroupBox)
        self.snapshotDisplayOptionsLayout.setSpacing(6)
        self.snapshotDisplayOptionsLayout.setContentsMargins(0, -1, 0, -1)
        self.snapshotDisplayOptionsLayout.setObjectName("snapshotDisplayOptionsLayout")
        self.snapshotDescriptionLimitCheckBox = QtGui.QCheckBox(self.snapshotDisplayOptionsGroupBox)
        self.snapshotDescriptionLimitCheckBox.setChecked(True)
        self.snapshotDescriptionLimitCheckBox.setObjectName("snapshotDescriptionLimitCheckBox")
        self.snapshotDisplayOptionsLayout.addWidget(self.snapshotDescriptionLimitCheckBox)
        self.snapshotDescriptionLimitSpinBox = QtGui.QSpinBox(self.snapshotDisplayOptionsGroupBox)
        self.snapshotDescriptionLimitSpinBox.setMinimum(20)
        self.snapshotDescriptionLimitSpinBox.setMaximum(50000)
        self.snapshotDescriptionLimitSpinBox.setSingleStep(5)
        self.snapshotDescriptionLimitSpinBox.setProperty("value", 80)
        self.snapshotDescriptionLimitSpinBox.setObjectName("snapshotDescriptionLimitSpinBox")
        self.snapshotDisplayOptionsLayout.addWidget(self.snapshotDescriptionLimitSpinBox)
        self.gridLayout_3.addWidget(self.snapshotDisplayOptionsGroupBox, 0, 0, 1, 1)
        self.processTabsFilterGroupBox = QtGui.QGroupBox(self.checkinOutPage)
        self.processTabsFilterGroupBox.setFlat(True)
        self.processTabsFilterGroupBox.setCheckable(True)
        self.processTabsFilterGroupBox.setObjectName("processTabsFilterGroupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.processTabsFilterGroupBox)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.flushTabsCachePushButton = QtGui.QPushButton(self.processTabsFilterGroupBox)
        self.flushTabsCachePushButton.setObjectName("flushTabsCachePushButton")
        self.gridLayout_4.addWidget(self.flushTabsCachePushButton, 5, 1, 1, 1)
        self.processTreeWidget = QtGui.QTreeWidget(self.processTabsFilterGroupBox)
        self.processTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.processTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.processTreeWidget.setObjectName("processTreeWidget")
        self.processTreeWidget.header().setDefaultSectionSize(240)
        self.processTreeWidget.header().setMinimumSectionSize(170)
        self.gridLayout_4.addWidget(self.processTreeWidget, 0, 0, 4, 2)
        self.processTabsMoveUpToolButton = QtGui.QToolButton(self.processTabsFilterGroupBox)
        self.processTabsMoveUpToolButton.setArrowType(QtCore.Qt.UpArrow)
        self.processTabsMoveUpToolButton.setObjectName("processTabsMoveUpToolButton")
        self.gridLayout_4.addWidget(self.processTabsMoveUpToolButton, 0, 2, 1, 1)
        self.processTabsMoveDownToolButton = QtGui.QToolButton(self.processTabsFilterGroupBox)
        self.processTabsMoveDownToolButton.setArrowType(QtCore.Qt.DownArrow)
        self.processTabsMoveDownToolButton.setObjectName("processTabsMoveDownToolButton")
        self.gridLayout_4.addWidget(self.processTabsMoveDownToolButton, 1, 2, 1, 1)
        self.cacheProcessTabsCheckBox = QtGui.QCheckBox(self.processTabsFilterGroupBox)
        self.cacheProcessTabsCheckBox.setObjectName("cacheProcessTabsCheckBox")
        self.gridLayout_4.addWidget(self.cacheProcessTabsCheckBox, 5, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_3.addWidget(self.processTabsFilterGroupBox, 2, 0, 1, 1)
        self.controlsTabsFilterGroupBox = QtGui.QGroupBox(self.checkinOutPage)
        self.controlsTabsFilterGroupBox.setFlat(True)
        self.controlsTabsFilterGroupBox.setCheckable(True)
        self.controlsTabsFilterGroupBox.setObjectName("controlsTabsFilterGroupBox")
        self.controlsTabsFilterLayout = QtGui.QGridLayout(self.controlsTabsFilterGroupBox)
        self.controlsTabsFilterLayout.setSpacing(6)
        self.controlsTabsFilterLayout.setContentsMargins(0, -1, 0, -1)
        self.controlsTabsFilterLayout.setObjectName("controlsTabsFilterLayout")
        self.controlsTabsMoveUpToolButton = QtGui.QToolButton(self.controlsTabsFilterGroupBox)
        self.controlsTabsMoveUpToolButton.setArrowType(QtCore.Qt.UpArrow)
        self.controlsTabsMoveUpToolButton.setObjectName("controlsTabsMoveUpToolButton")
        self.controlsTabsFilterLayout.addWidget(self.controlsTabsMoveUpToolButton, 0, 1, 1, 1)
        self.controlsTabsTreeWidget = QtGui.QTreeWidget(self.controlsTabsFilterGroupBox)
        self.controlsTabsTreeWidget.setTabKeyNavigation(True)
        self.controlsTabsTreeWidget.setAlternatingRowColors(True)
        self.controlsTabsTreeWidget.setRootIsDecorated(False)
        self.controlsTabsTreeWidget.setUniformRowHeights(True)
        self.controlsTabsTreeWidget.setItemsExpandable(False)
        self.controlsTabsTreeWidget.setAnimated(True)
        self.controlsTabsTreeWidget.setExpandsOnDoubleClick(False)
        self.controlsTabsTreeWidget.setObjectName("controlsTabsTreeWidget")
        self.controlsTabsTreeWidget.header().setDefaultSectionSize(240)
        self.controlsTabsTreeWidget.header().setMinimumSectionSize(170)
        self.controlsTabsFilterLayout.addWidget(self.controlsTabsTreeWidget, 0, 0, 3, 1)
        self.controlsTabsMoveDownToolButton = QtGui.QToolButton(self.controlsTabsFilterGroupBox)
        self.controlsTabsMoveDownToolButton.setArrowType(QtCore.Qt.DownArrow)
        self.controlsTabsMoveDownToolButton.setObjectName("controlsTabsMoveDownToolButton")
        self.controlsTabsFilterLayout.addWidget(self.controlsTabsMoveDownToolButton, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.controlsTabsFilterGroupBox, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.configToolBox.addItem(self.checkinOutPage, "")
        self.globalCofigPage = QtGui.QWidget()
        self.globalCofigPage.setObjectName("globalCofigPage")
        self.configToolBox.addItem(self.globalCofigPage, "")
        self.currentEnvironmentPage = QtGui.QWidget()
        self.currentEnvironmentPage.setGeometry(QtCore.QRect(0, 0, 464, 508))
        self.currentEnvironmentPage.setObjectName("currentEnvironmentPage")
        self.verticalLayout = QtGui.QVBoxLayout(self.currentEnvironmentPage)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.currentWorkdirLable = QtGui.QLabel(self.currentEnvironmentPage)
        self.currentWorkdirLable.setObjectName("currentWorkdirLable")
        self.gridLayout_2.addWidget(self.currentWorkdirLable, 0, 0, 1, 1)
        self.currentWorkdirLineEdit = QtGui.QLineEdit(self.currentEnvironmentPage)
        self.currentWorkdirLineEdit.setReadOnly(True)
        self.currentWorkdirLineEdit.setObjectName("currentWorkdirLineEdit")
        self.gridLayout_2.addWidget(self.currentWorkdirLineEdit, 0, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 100)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.configToolBox.addItem(self.currentEnvironmentPage, "")
        self.gridLayout_6.addWidget(self.configToolBox, 0, 0, 1, 1)

        self.retranslateUi(configuration_dialog)
        self.configToolBox.setCurrentIndex(0)
        self.configToolBox.layout().setSpacing(6)
        QtCore.QObject.connect(self.snapshotDescriptionLimitCheckBox, QtCore.SIGNAL("toggled(bool)"), self.snapshotDescriptionLimitSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(configuration_dialog)
        configuration_dialog.setTabOrder(self.userNameLineEdit, self.passwordLineEdit)
        configuration_dialog.setTabOrder(self.passwordLineEdit, self.generateTicketButton)
        configuration_dialog.setTabOrder(self.generateTicketButton, self.tacticEnvLineEdit)
        configuration_dialog.setTabOrder(self.tacticEnvLineEdit, self.tacticInstallDirLineEdit)
        configuration_dialog.setTabOrder(self.tacticInstallDirLineEdit, self.buttonBox)
        configuration_dialog.setTabOrder(self.buttonBox, self.currentWorkdirLineEdit)

    def retranslateUi(self, configuration_dialog):
        configuration_dialog.setWindowTitle(QtGui.QApplication.translate("configuration_dialog", "TACTIC Handler configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.environmentsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Tactic Environments:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticEnvLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic Data dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticInstallDirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic Install dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.addTacticEnv.setText(QtGui.QApplication.translate("configuration_dialog", "Add Tactic environments to system", None, QtGui.QApplication.UnicodeUTF8))
        self.authorizingGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Authorization:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectToServerButton.setText(QtGui.QApplication.translate("configuration_dialog", "Try to connect", None, QtGui.QApplication.UnicodeUTF8))
        self.userNameLable.setText(QtGui.QApplication.translate("configuration_dialog", "User Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLable.setText(QtGui.QApplication.translate("configuration_dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.loginStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateTicketButton.setText(QtGui.QApplication.translate("configuration_dialog", "Generate new Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticServerLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic server:", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.serverPage), QtGui.QApplication.translate("configuration_dialog", "TACTIC Server", None, QtGui.QApplication.UnicodeUTF8))
        self.templateProjectsLabel.setText(QtGui.QApplication.translate("configuration_dialog", " Template Projects ", None, QtGui.QApplication.UnicodeUTF8))
        self.colorSchemeHintLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Scheme: ", None, QtGui.QApplication.UnicodeUTF8))
        self.createProjectsLable.setText(QtGui.QApplication.translate("configuration_dialog", "Create new Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.createProjectPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.setToolTip(QtGui.QApplication.translate("configuration_dialog", "Right click for menu", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.setStatusTip(QtGui.QApplication.translate("configuration_dialog", "Right click for menu", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Category/Title", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("configuration_dialog", "Namespace (template)", None, QtGui.QApplication.UnicodeUTF8))
        self.projectsTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("configuration_dialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.currentProjectLabel.setText(QtGui.QApplication.translate("configuration_dialog", " Current Project ", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.projectPage), QtGui.QApplication.translate("configuration_dialog", "Project (restart required to apply)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkoutMiscOpitionsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickOpenCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "DoubleClick for Open", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsSeparateCheckoutCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Display versions separate", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkoutPage), QtGui.QApplication.translate("configuration_dialog", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMiscOpitionsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickSaveCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "DoubleClick for Save", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsSeparateCheckinCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Display versions separate", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Current repository paths:", None, QtGui.QApplication.UnicodeUTF8))
        self.assetBaseDirCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Asset base dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.sandboxCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Sandbox dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.localRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Local repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Client repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.handoffCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Handoff dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Custom repository path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("configuration_dialog", "Custom Repo name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("configuration_dialog", "Repo path:", None, QtGui.QApplication.UnicodeUTF8))
        self.addCustomRepoToListPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editCustomRepoPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCustomRepoPushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Show custom repos", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("configuration_dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("configuration_dialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkinPage), QtGui.QApplication.translate("configuration_dialog", "Checkin", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotDisplayOptionsGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Snapshots display options:", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotDescriptionLimitCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Limit snapshot description preview (symbols)", None, QtGui.QApplication.UnicodeUTF8))
        self.processTabsFilterGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Filter Process Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.flushTabsCachePushButton.setText(QtGui.QApplication.translate("configuration_dialog", "Flush Tabs cache", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Category/Title", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.processTabsMoveUpToolButton.setText(QtGui.QApplication.translate("configuration_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.processTabsMoveDownToolButton.setText(QtGui.QApplication.translate("configuration_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cacheProcessTabsCheckBox.setText(QtGui.QApplication.translate("configuration_dialog", "Cache Tabs (faster launch)", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsTabsFilterGroupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Filter Control Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsTabsMoveUpToolButton.setText(QtGui.QApplication.translate("configuration_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsTabsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Tab Name", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsTabsTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Tab Label", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsTabsMoveDownToolButton.setText(QtGui.QApplication.translate("configuration_dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkinOutPage), QtGui.QApplication.translate("configuration_dialog", "Checkin/Checkout display (for current Project and environment)", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.globalCofigPage), QtGui.QApplication.translate("configuration_dialog", "Global Config", None, QtGui.QApplication.UnicodeUTF8))
        self.currentWorkdirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Current Workdir:", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.currentEnvironmentPage), QtGui.QApplication.translate("configuration_dialog", "Current Environment Options", None, QtGui.QApplication.UnicodeUTF8))

