# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_search_options.ui'
#
# Created: Sat Feb 20 15:06:45 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_searchOptionsGroupBox(object):
    def setupUi(self, searchOptionsGroupBox):
        searchOptionsGroupBox.setObjectName("searchOptionsGroupBox")
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(searchOptionsGroupBox.sizePolicy().hasHeightForWidth())
        searchOptionsGroupBox.setSizePolicy(sizePolicy)
        searchOptionsGroupBox.setFlat(True)
        self.gridLayout = QtGui.QGridLayout(searchOptionsGroupBox)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(4, 2, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.sortByGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.sortByGroupBox.setFlat(True)
        self.sortByGroupBox.setObjectName("sortByGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.sortByGroupBox)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtGui.QRadioButton(self.sortByGroupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.sortByGroupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_4 = QtGui.QRadioButton(self.sortByGroupBox)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.sortByGroupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.sortByGroupBox, 2, 0, 1, 3)
        self.searchByGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.searchByGroupBox.setFlat(True)
        self.searchByGroupBox.setObjectName("searchByGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.searchByGroupBox)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchNameRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchNameRadioButton.setChecked(True)
        self.searchNameRadioButton.setObjectName("searchNameRadioButton")
        self.horizontalLayout_2.addWidget(self.searchNameRadioButton)
        self.searchCodeRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchCodeRadioButton.setObjectName("searchCodeRadioButton")
        self.horizontalLayout_2.addWidget(self.searchCodeRadioButton)
        self.searchDescriptionRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchDescriptionRadioButton.setObjectName("searchDescriptionRadioButton")
        self.horizontalLayout_2.addWidget(self.searchDescriptionRadioButton)
        self.searchKeywordsRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchKeywordsRadioButton.setObjectName("searchKeywordsRadioButton")
        self.horizontalLayout_2.addWidget(self.searchKeywordsRadioButton)
        self.searchParentCodeRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchParentCodeRadioButton.setObjectName("searchParentCodeRadioButton")
        self.horizontalLayout_2.addWidget(self.searchParentCodeRadioButton)
        self.parentsComboBox = QtGui.QComboBox(self.searchByGroupBox)
        self.parentsComboBox.setEditable(True)
        self.parentsComboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.parentsComboBox.setObjectName("parentsComboBox")
        self.parentsComboBox.addItem("")
        self.parentsComboBox.addItem("")
        self.parentsComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.parentsComboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.searchByGroupBox, 1, 0, 1, 3)
        self.miscGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.miscGroupBox.setFlat(True)
        self.miscGroupBox.setObjectName("miscGroupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.miscGroupBox)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveAsDefaultToolButton = QtGui.QToolButton(self.miscGroupBox)
        self.saveAsDefaultToolButton.setAutoRaise(True)
        self.saveAsDefaultToolButton.setObjectName("saveAsDefaultToolButton")
        self.horizontalLayout_3.addWidget(self.saveAsDefaultToolButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtGui.QLabel(self.miscGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spinBox = QtGui.QSpinBox(self.miscGroupBox)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(200)
        self.spinBox.setSingleStep(5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.showAllProcessCheckBox = QtGui.QCheckBox(self.miscGroupBox)
        self.showAllProcessCheckBox.setChecked(True)
        self.showAllProcessCheckBox.setObjectName("showAllProcessCheckBox")
        self.horizontalLayout_3.addWidget(self.showAllProcessCheckBox)
        self.gridLayout.addWidget(self.miscGroupBox, 3, 0, 1, 3)

        self.retranslateUi(searchOptionsGroupBox)
        QtCore.QMetaObject.connectSlotsByName(searchOptionsGroupBox)
        searchOptionsGroupBox.setTabOrder(self.searchNameRadioButton, self.searchCodeRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchCodeRadioButton, self.searchDescriptionRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchDescriptionRadioButton, self.searchKeywordsRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchKeywordsRadioButton, self.radioButton)
        searchOptionsGroupBox.setTabOrder(self.radioButton, self.radioButton_2)
        searchOptionsGroupBox.setTabOrder(self.radioButton_2, self.radioButton_4)
        searchOptionsGroupBox.setTabOrder(self.radioButton_4, self.radioButton_3)
        searchOptionsGroupBox.setTabOrder(self.radioButton_3, self.showAllProcessCheckBox)
        searchOptionsGroupBox.setTabOrder(self.showAllProcessCheckBox, self.spinBox)
        searchOptionsGroupBox.setTabOrder(self.spinBox, self.saveAsDefaultToolButton)

    def retranslateUi(self, searchOptionsGroupBox):
        searchOptionsGroupBox.setWindowTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        searchOptionsGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.sortByGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Sort by:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Search Code", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Timestamp", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.searchByGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Search by:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchNameRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCodeRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Search Code", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDescriptionRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.searchKeywordsRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.searchParentCodeRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Parent Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(0, QtGui.QApplication.translate("searchOptionsGroupBox", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(1, QtGui.QApplication.translate("searchOptionsGroupBox", "scenes_code", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(2, QtGui.QApplication.translate("searchOptionsGroupBox", "sets_code", None, QtGui.QApplication.UnicodeUTF8))
        self.miscGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsDefaultToolButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Save as Default", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Display limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.showAllProcessCheckBox.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Show all Process", None, QtGui.QApplication.UnicodeUTF8))

