# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_search_options.ui'
#
# Created: Sat May 14 23:35:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_searchOptionsGroupBox(object):
    def setupUi(self, searchOptionsGroupBox):
        searchOptionsGroupBox.setObjectName("searchOptionsGroupBox")
        searchOptionsGroupBox.resize(539, 180)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(searchOptionsGroupBox.sizePolicy().hasHeightForWidth())
        searchOptionsGroupBox.setSizePolicy(sizePolicy)
        searchOptionsGroupBox.setFlat(True)
        self.gridLayout = QtGui.QGridLayout(searchOptionsGroupBox)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(4, 2, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.sortByGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.sortByGroupBox.setFlat(True)
        self.sortByGroupBox.setObjectName("sortByGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.sortByGroupBox)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sortNameRadioButton = QtGui.QRadioButton(self.sortByGroupBox)
        self.sortNameRadioButton.setObjectName("sortNameRadioButton")
        self.horizontalLayout.addWidget(self.sortNameRadioButton)
        self.sortCodeRadioButton = QtGui.QRadioButton(self.sortByGroupBox)
        self.sortCodeRadioButton.setObjectName("sortCodeRadioButton")
        self.horizontalLayout.addWidget(self.sortCodeRadioButton)
        self.sortTimestampRadioButton = QtGui.QRadioButton(self.sortByGroupBox)
        self.sortTimestampRadioButton.setChecked(True)
        self.sortTimestampRadioButton.setObjectName("sortTimestampRadioButton")
        self.horizontalLayout.addWidget(self.sortTimestampRadioButton)
        self.sortNothingRadioButton = QtGui.QRadioButton(self.sortByGroupBox)
        self.sortNothingRadioButton.setObjectName("sortNothingRadioButton")
        self.horizontalLayout.addWidget(self.sortNothingRadioButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.sortByGroupBox, 2, 0, 1, 3)
        self.searchByGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.searchByGroupBox.setFlat(True)
        self.searchByGroupBox.setObjectName("searchByGroupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.searchByGroupBox)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchNameRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchNameRadioButton.setChecked(True)
        self.searchNameRadioButton.setObjectName("searchNameRadioButton")
        self.horizontalLayout_2.addWidget(self.searchNameRadioButton)
        self.searchCodeRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchCodeRadioButton.setObjectName("searchCodeRadioButton")
        self.horizontalLayout_2.addWidget(self.searchCodeRadioButton)
        self.searchDescriptionRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchDescriptionRadioButton.setObjectName("searchDescriptionRadioButton")
        self.horizontalLayout_2.addWidget(self.searchDescriptionRadioButton)
        self.searchKeywordsRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchKeywordsRadioButton.setObjectName("searchKeywordsRadioButton")
        self.horizontalLayout_2.addWidget(self.searchKeywordsRadioButton)
        self.searchParentCodeRadioButton = QtGui.QRadioButton(self.searchByGroupBox)
        self.searchParentCodeRadioButton.setObjectName("searchParentCodeRadioButton")
        self.horizontalLayout_2.addWidget(self.searchParentCodeRadioButton)
        self.parentsComboBox = QtGui.QComboBox(self.searchByGroupBox)
        self.parentsComboBox.setEditable(True)
        self.parentsComboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.parentsComboBox.setObjectName("parentsComboBox")
        self.parentsComboBox.addItem("")
        self.parentsComboBox.addItem("")
        self.parentsComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.parentsComboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.searchByGroupBox, 1, 0, 1, 3)
        self.miscGroupBox = QtGui.QGroupBox(searchOptionsGroupBox)
        self.miscGroupBox.setFlat(True)
        self.miscGroupBox.setObjectName("miscGroupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.miscGroupBox)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveAsDefaultsPushButton = QtGui.QPushButton(self.miscGroupBox)
        self.saveAsDefaultsPushButton.setObjectName("saveAsDefaultsPushButton")
        self.horizontalLayout_3.addWidget(self.saveAsDefaultsPushButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtGui.QLabel(self.miscGroupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.displayLimitSpinBox = QtGui.QSpinBox(self.miscGroupBox)
        self.displayLimitSpinBox.setMinimum(5)
        self.displayLimitSpinBox.setMaximum(200)
        self.displayLimitSpinBox.setSingleStep(5)
        self.displayLimitSpinBox.setObjectName("displayLimitSpinBox")
        self.horizontalLayout_3.addWidget(self.displayLimitSpinBox)
        self.showAllProcessCheckBox = QtGui.QCheckBox(self.miscGroupBox)
        self.showAllProcessCheckBox.setChecked(True)
        self.showAllProcessCheckBox.setObjectName("showAllProcessCheckBox")
        self.horizontalLayout_3.addWidget(self.showAllProcessCheckBox)
        self.gridLayout.addWidget(self.miscGroupBox, 3, 0, 1, 3)

        self.retranslateUi(searchOptionsGroupBox)
        QtCore.QMetaObject.connectSlotsByName(searchOptionsGroupBox)
        searchOptionsGroupBox.setTabOrder(self.searchNameRadioButton, self.searchCodeRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchCodeRadioButton, self.searchDescriptionRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchDescriptionRadioButton, self.searchKeywordsRadioButton)
        searchOptionsGroupBox.setTabOrder(self.searchKeywordsRadioButton, self.sortNameRadioButton)
        searchOptionsGroupBox.setTabOrder(self.sortNameRadioButton, self.sortCodeRadioButton)
        searchOptionsGroupBox.setTabOrder(self.sortCodeRadioButton, self.sortTimestampRadioButton)
        searchOptionsGroupBox.setTabOrder(self.sortTimestampRadioButton, self.sortNothingRadioButton)
        searchOptionsGroupBox.setTabOrder(self.sortNothingRadioButton, self.showAllProcessCheckBox)
        searchOptionsGroupBox.setTabOrder(self.showAllProcessCheckBox, self.displayLimitSpinBox)
        searchOptionsGroupBox.setTabOrder(self.displayLimitSpinBox, self.saveAsDefaultsPushButton)

    def retranslateUi(self, searchOptionsGroupBox):
        searchOptionsGroupBox.setWindowTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        searchOptionsGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.sortByGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Sort by:", None, QtGui.QApplication.UnicodeUTF8))
        self.sortNameRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.sortCodeRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Search Code", None, QtGui.QApplication.UnicodeUTF8))
        self.sortTimestampRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Timestamp", None, QtGui.QApplication.UnicodeUTF8))
        self.sortNothingRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Nothing", None, QtGui.QApplication.UnicodeUTF8))
        self.searchByGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Search by:", None, QtGui.QApplication.UnicodeUTF8))
        self.searchNameRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.searchCodeRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Search Code", None, QtGui.QApplication.UnicodeUTF8))
        self.searchDescriptionRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.searchKeywordsRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.searchParentCodeRadioButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Parent Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(0, QtGui.QApplication.translate("searchOptionsGroupBox", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(1, QtGui.QApplication.translate("searchOptionsGroupBox", "scenes_code", None, QtGui.QApplication.UnicodeUTF8))
        self.parentsComboBox.setItemText(2, QtGui.QApplication.translate("searchOptionsGroupBox", "sets_code", None, QtGui.QApplication.UnicodeUTF8))
        self.miscGroupBox.setTitle(QtGui.QApplication.translate("searchOptionsGroupBox", "Misc:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsDefaultsPushButton.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Save as Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Display limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.showAllProcessCheckBox.setText(QtGui.QApplication.translate("searchOptionsGroupBox", "Show all Process", None, QtGui.QApplication.UnicodeUTF8))

