# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkin\ui_checkin_tree.ui'
#
# Created: Sat Nov 05 23:28:24 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_checkInTree(object):
    def setupUi(self, checkInTree):
        checkInTree.setObjectName("checkInTree")
        checkInTree.setMinimumSize(QtCore.QSize(400, 250))
        self.checkinTreeLayout = QtGui.QGridLayout(checkInTree)
        self.checkinTreeLayout.setSpacing(0)
        self.checkinTreeLayout.setContentsMargins(0, 0, 0, 8)
        self.checkinTreeLayout.setObjectName("checkinTreeLayout")
        self.descriptionSplitter = QtGui.QSplitter(checkInTree)
        self.descriptionSplitter.setOrientation(QtCore.Qt.Vertical)
        self.descriptionSplitter.setObjectName("descriptionSplitter")
        self.commentsSplitter = QtGui.QSplitter(self.descriptionSplitter)
        self.commentsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.commentsSplitter.setObjectName("commentsSplitter")
        self.layoutWidget = QtGui.QWidget(self.commentsSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.searchOptionsSplitter = QtGui.QSplitter(self.layoutWidget)
        self.searchOptionsSplitter.setOrientation(QtCore.Qt.Vertical)
        self.searchOptionsSplitter.setObjectName("searchOptionsSplitter")
        self.gridLayout.addWidget(self.searchOptionsSplitter, 1, 0, 1, 6)
        self.searchLineEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet("QLineEdit {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    show-decoration-selected: 1;\n"
"    padding: 0px 8px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 64), stop:1 rgba(255, 255, 255, 0));\n"
"    background-position: bottom left;\n"
"    background-image: url(\":/ui_check/gliph/search_16.png\");\n"
"    background-repeat: fixed;\n"
"    selection-background-color: darkgray;\n"
"    padding-left: 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: white;\n"
"    background-image: url(\":/ui_check/gliph/searchHover_16.png\");\n"
"}")
        self.searchLineEdit.setFrame(False)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayout.addWidget(self.searchLineEdit, 0, 0, 1, 1)
        self.findOpenedPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findOpenedPushButton.sizePolicy().hasHeightForWidth())
        self.findOpenedPushButton.setSizePolicy(sizePolicy)
        self.findOpenedPushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.findOpenedPushButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.findOpenedPushButton.setObjectName("findOpenedPushButton")
        self.gridLayout.addWidget(self.findOpenedPushButton, 0, 3, 1, 1)
        self.addNewtButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addNewtButton.sizePolicy().hasHeightForWidth())
        self.addNewtButton.setSizePolicy(sizePolicy)
        self.addNewtButton.setMinimumSize(QtCore.QSize(75, 0))
        self.addNewtButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.addNewtButton.setObjectName("addNewtButton")
        self.gridLayout.addWidget(self.addNewtButton, 0, 2, 1, 1)
        self.refreshToolButton = QtGui.QToolButton(self.layoutWidget)
        self.refreshToolButton.setMaximumSize(QtCore.QSize(16777215, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui_main/gliph/gear_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshToolButton.setIcon(icon)
        self.refreshToolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.refreshToolButton.setAutoRaise(True)
        self.refreshToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.refreshToolButton.setObjectName("refreshToolButton")
        self.gridLayout.addWidget(self.refreshToolButton, 0, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.commentsSplitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playblastGroupBox = QtGui.QGroupBox(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playblastGroupBox.sizePolicy().hasHeightForWidth())
        self.playblastGroupBox.setSizePolicy(sizePolicy)
        self.playblastGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.playblastGroupBox.setFlat(True)
        self.playblastGroupBox.setObjectName("playblastGroupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.playblastGroupBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imagesSplitter = QtGui.QSplitter(self.playblastGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesSplitter.sizePolicy().hasHeightForWidth())
        self.imagesSplitter.setSizePolicy(sizePolicy)
        self.imagesSplitter.setMinimumSize(QtCore.QSize(0, 376))
        self.imagesSplitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.imagesSplitter.setOrientation(QtCore.Qt.Vertical)
        self.imagesSplitter.setObjectName("imagesSplitter")
        self.layoutWidget1 = QtGui.QWidget(self.imagesSplitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.iconsLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.iconsLayout.setSpacing(0)
        self.iconsLayout.setContentsMargins(0, 0, 0, 0)
        self.iconsLayout.setObjectName("iconsLayout")
        self.verticalLayoutWidget = QtGui.QWidget(self.imagesSplitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.playblastLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.playblastLayout.setSpacing(0)
        self.playblastLayout.setContentsMargins(0, 0, 0, 0)
        self.playblastLayout.setContentsMargins(0, 0, 0, 0)
        self.playblastLayout.setObjectName("playblastLayout")
        self.verticalLayout_4.addWidget(self.imagesSplitter)
        self.verticalLayout_2.addWidget(self.playblastGroupBox)
        self.dropPlateSplitter = QtGui.QSplitter(self.descriptionSplitter)
        self.dropPlateSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.dropPlateSplitter.setObjectName("dropPlateSplitter")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.dropPlateSplitter)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.descriptionLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.descriptionLayout.setSpacing(0)
        self.descriptionLayout.setContentsMargins(0, 0, 0, 0)
        self.descriptionLayout.setContentsMargins(0, 0, 0, 0)
        self.descriptionLayout.setObjectName("descriptionLayout")
        self.commentsGroupBox = QtGui.QGroupBox(self.verticalLayoutWidget_4)
        self.commentsGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.commentsGroupBox.setFlat(True)
        self.commentsGroupBox.setObjectName("commentsGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.commentsGroupBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editorLayout = QtGui.QVBoxLayout()
        self.editorLayout.setSpacing(0)
        self.editorLayout.setObjectName("editorLayout")
        self.verticalLayout.addLayout(self.editorLayout)
        self.checkinOptionsSplitter = QtGui.QSplitter(self.commentsGroupBox)
        self.checkinOptionsSplitter.setOrientation(QtCore.Qt.Vertical)
        self.checkinOptionsSplitter.setObjectName("checkinOptionsSplitter")
        self.descriptionTextEdit = QtGui.QTextEdit(self.checkinOptionsSplitter)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.checkinOptionsSplitter)
        self.descriptionLayout.addWidget(self.commentsGroupBox)
        self.gridLayoutWidget = QtGui.QWidget(self.dropPlateSplitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.dropPlateLayout = QtGui.QVBoxLayout(self.gridLayoutWidget)
        self.dropPlateLayout.setSpacing(6)
        self.dropPlateLayout.setContentsMargins(0, 1, 0, 8)
        self.dropPlateLayout.setObjectName("dropPlateLayout")
        self.checkinTreeLayout.addWidget(self.descriptionSplitter, 0, 0, 1, 6)
        self.toggleSaveOptionsToolButton = QtGui.QToolButton(checkInTree)
        self.toggleSaveOptionsToolButton.setMinimumSize(QtCore.QSize(0, 22))
        self.toggleSaveOptionsToolButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toggleSaveOptionsToolButton.setCheckable(True)
        self.toggleSaveOptionsToolButton.setChecked(True)
        self.toggleSaveOptionsToolButton.setAutoRaise(True)
        self.toggleSaveOptionsToolButton.setArrowType(QtCore.Qt.UpArrow)
        self.toggleSaveOptionsToolButton.setObjectName("toggleSaveOptionsToolButton")
        self.checkinTreeLayout.addWidget(self.toggleSaveOptionsToolButton, 1, 0, 1, 1)
        self.formatTypeComboBox = QtGui.QComboBox(checkInTree)
        self.formatTypeComboBox.setObjectName("formatTypeComboBox")
        self.checkinTreeLayout.addWidget(self.formatTypeComboBox, 1, 1, 1, 1)
        self.savePushButton = QtGui.QToolButton(checkInTree)
        self.savePushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePushButton.sizePolicy().hasHeightForWidth())
        self.savePushButton.setSizePolicy(sizePolicy)
        self.savePushButton.setMinimumSize(QtCore.QSize(75, 22))
        self.savePushButton.setChecked(False)
        self.savePushButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.savePushButton.setAutoRaise(True)
        self.savePushButton.setObjectName("savePushButton")
        self.checkinTreeLayout.addWidget(self.savePushButton, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.checkinTreeLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.contextLabel = QtGui.QLabel(checkInTree)
        self.contextLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.contextLabel.setObjectName("contextLabel")
        self.checkinTreeLayout.addWidget(self.contextLabel, 1, 4, 1, 1)
        self.contextLineEdit = QtGui.QLineEdit(checkInTree)
        self.contextLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextLineEdit.sizePolicy().hasHeightForWidth())
        self.contextLineEdit.setSizePolicy(sizePolicy)
        self.contextLineEdit.setObjectName("contextLineEdit")
        self.checkinTreeLayout.addWidget(self.contextLineEdit, 1, 5, 1, 1)
        self.checkinTreeLayout.setColumnMinimumWidth(5, 100)
        self.checkinTreeLayout.setColumnStretch(3, 1)
        self.checkinTreeLayout.setColumnStretch(5, 1)

        self.retranslateUi(checkInTree)
        QtCore.QMetaObject.connectSlotsByName(checkInTree)
        checkInTree.setTabOrder(self.searchLineEdit, self.descriptionTextEdit)

    def retranslateUi(self, checkInTree):
        self.findOpenedPushButton.setText(QtGui.QApplication.translate("checkInTree", "Find Opened", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewtButton.setText(QtGui.QApplication.translate("checkInTree", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastGroupBox.setTitle(QtGui.QApplication.translate("checkInTree", "Preview images:", None, QtGui.QApplication.UnicodeUTF8))
        self.commentsGroupBox.setTitle(QtGui.QApplication.translate("checkInTree", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionTextEdit.setHtml(QtGui.QApplication.translate("checkInTree", "", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setText(QtGui.QApplication.translate("checkInTree", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.contextLabel.setText(QtGui.QApplication.translate("checkInTree", "Context:", None, QtGui.QApplication.UnicodeUTF8))

import lib.ui.resources_rc
