# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_conf.ui'
#
# Created: Fri Jan 22 20:48:03 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_configuration_dialog(object):
    def setupUi(self, configuration_dialog):
        configuration_dialog.setObjectName("configuration_dialog")
        configuration_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        configuration_dialog.resize(972, 787)
        configuration_dialog.setMinimumSize(QtCore.QSize(480, 380))
        configuration_dialog.setSizeGripEnabled(True)
        configuration_dialog.setModal(True)
        self.configToolBox = QtGui.QToolBox(configuration_dialog)
        self.configToolBox.setGeometry(QtCore.QRect(15, 9, 451, 391))
        self.configToolBox.setStyleSheet("QToolBox::tab {\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"    padding: 3px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 25), stop: 1 rgba(175, 175, 175, 0));\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 rgba(175, 175, 175, 50), stop: 1 rgba(175, 175, 175, 0));\n"
"    border: 1px solid rgba(128, 128, 128, 75);\n"
"}\n"
"QToolBox::tab:selected {\n"
"    font: italic;\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-color:  rgba(75, 75, 75, 75);\n"
"    border-radius: 1px;\n"
"}")
        self.configToolBox.setObjectName("configToolBox")
        self.scenePage = QtGui.QWidget()
        self.scenePage.setGeometry(QtCore.QRect(0, 0, 451, 307))
        self.scenePage.setObjectName("scenePage")
        self.verticalLayout = QtGui.QVBoxLayout(self.scenePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.currentWorkdirLable = QtGui.QLabel(self.scenePage)
        self.currentWorkdirLable.setObjectName("currentWorkdirLable")
        self.gridLayout_2.addWidget(self.currentWorkdirLable, 0, 0, 1, 1)
        self.currentWorkdirLineEdit = QtGui.QLineEdit(self.scenePage)
        self.currentWorkdirLineEdit.setReadOnly(True)
        self.currentWorkdirLineEdit.setObjectName("currentWorkdirLineEdit")
        self.gridLayout_2.addWidget(self.currentWorkdirLineEdit, 0, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 100)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.configToolBox.addItem(self.scenePage, "")
        self.loginPage = QtGui.QWidget()
        self.loginPage.setGeometry(QtCore.QRect(0, 0, 451, 307))
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.loginPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tacticEnvLineEdit = QtGui.QLineEdit(self.loginPage)
        self.tacticEnvLineEdit.setObjectName("tacticEnvLineEdit")
        self.gridLayout_3.addWidget(self.tacticEnvLineEdit, 4, 1, 1, 2)
        self.tacticAssetDirLineEdit = QtGui.QLineEdit(self.loginPage)
        self.tacticAssetDirLineEdit.setObjectName("tacticAssetDirLineEdit")
        self.gridLayout_3.addWidget(self.tacticAssetDirLineEdit, 5, 1, 1, 2)
        self.tacticInstallDirLable = QtGui.QLabel(self.loginPage)
        self.tacticInstallDirLable.setObjectName("tacticInstallDirLable")
        self.gridLayout_3.addWidget(self.tacticInstallDirLable, 6, 0, 1, 1)
        self.tacticInstallDirLineEdit = QtGui.QLineEdit(self.loginPage)
        self.tacticInstallDirLineEdit.setObjectName("tacticInstallDirLineEdit")
        self.gridLayout_3.addWidget(self.tacticInstallDirLineEdit, 6, 1, 1, 2)
        self.tacticServerLable = QtGui.QLabel(self.loginPage)
        self.tacticServerLable.setObjectName("tacticServerLable")
        self.gridLayout_3.addWidget(self.tacticServerLable, 7, 0, 1, 1)
        self.tacticAssetDirLable = QtGui.QLabel(self.loginPage)
        self.tacticAssetDirLable.setObjectName("tacticAssetDirLable")
        self.gridLayout_3.addWidget(self.tacticAssetDirLable, 5, 0, 1, 1)
        self.tacticEnvLable = QtGui.QLabel(self.loginPage)
        self.tacticEnvLable.setObjectName("tacticEnvLable")
        self.gridLayout_3.addWidget(self.tacticEnvLable, 4, 0, 1, 1)
        self.generateTicketButton = QtGui.QPushButton(self.loginPage)
        self.generateTicketButton.setObjectName("generateTicketButton")
        self.gridLayout_3.addWidget(self.generateTicketButton, 2, 1, 1, 2)
        self.loginStatusLable = QtGui.QLabel(self.loginPage)
        self.loginStatusLable.setObjectName("loginStatusLable")
        self.gridLayout_3.addWidget(self.loginStatusLable, 2, 0, 1, 1)
        self.userNameLineEdit = QtGui.QLineEdit(self.loginPage)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.gridLayout_3.addWidget(self.userNameLineEdit, 0, 1, 1, 2)
        self.tacticServerLineEdit = QtGui.QLineEdit(self.loginPage)
        self.tacticServerLineEdit.setObjectName("tacticServerLineEdit")
        self.gridLayout_3.addWidget(self.tacticServerLineEdit, 7, 1, 1, 2)
        self.passwordLineEdit = QtGui.QLineEdit(self.loginPage)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout_3.addWidget(self.passwordLineEdit, 1, 1, 1, 2)
        self.passwordLable = QtGui.QLabel(self.loginPage)
        self.passwordLable.setObjectName("passwordLable")
        self.gridLayout_3.addWidget(self.passwordLable, 1, 0, 1, 1)
        self.userNameLable = QtGui.QLabel(self.loginPage)
        self.userNameLable.setObjectName("userNameLable")
        self.gridLayout_3.addWidget(self.userNameLable, 0, 0, 1, 1)
        self.tacticStatusLable = QtGui.QLabel(self.loginPage)
        self.tacticStatusLable.setObjectName("tacticStatusLable")
        self.gridLayout_3.addWidget(self.tacticStatusLable, 8, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 9, 2, 1, 1)
        self.connectToServerButton = QtGui.QPushButton(self.loginPage)
        self.connectToServerButton.setMinimumSize(QtCore.QSize(120, 0))
        self.connectToServerButton.setObjectName("connectToServerButton")
        self.gridLayout_3.addWidget(self.connectToServerButton, 8, 1, 1, 1)
        self.addTacticEnv = QtGui.QPushButton(self.loginPage)
        self.addTacticEnv.setObjectName("addTacticEnv")
        self.gridLayout_3.addWidget(self.addTacticEnv, 8, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.configToolBox.addItem(self.loginPage, "")
        self.projectPage = QtGui.QWidget()
        self.projectPage.setGeometry(QtCore.QRect(0, 0, 451, 307))
        self.projectPage.setObjectName("projectPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.projectPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.projectPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.configToolBox.addItem(self.projectPage, "")
        self.checkinOutPage = QtGui.QWidget()
        self.checkinOutPage.setGeometry(QtCore.QRect(0, 0, 451, 307))
        self.checkinOutPage.setObjectName("checkinOutPage")
        self.gridLayout_5 = QtGui.QGridLayout(self.checkinOutPage)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(6, 6, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtGui.QGroupBox(self.checkinOutPage)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(6, 6, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.processTreeWidget = QtGui.QTreeWidget(self.groupBox)
        self.processTreeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.processTreeWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.processTreeWidget.setObjectName("processTreeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        self.processTreeWidget.header().setDefaultSectionSize(170)
        self.verticalLayout_4.addWidget(self.processTreeWidget)
        self.gridLayout_5.addWidget(self.groupBox, 0, 1, 1, 1)
        self.configToolBox.addItem(self.checkinOutPage, "")
        self.buttonBox = QtGui.QDialogButtonBox(configuration_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(9, 442, 371, 23))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(configuration_dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(640, 450, 217, 147))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.projectInfoCodeLabel = QtGui.QLabel(self.layoutWidget)
        self.projectInfoCodeLabel.setText("")
        self.projectInfoCodeLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.projectInfoCodeLabel.setObjectName("projectInfoCodeLabel")
        self.gridLayout_4.addWidget(self.projectInfoCodeLabel, 2, 1, 1, 1)
        self.projectCodeLabel = QtGui.QLabel(self.layoutWidget)
        self.projectCodeLabel.setObjectName("projectCodeLabel")
        self.gridLayout_4.addWidget(self.projectCodeLabel, 2, 0, 1, 1)
        self.currentProjectLable = QtGui.QLabel(self.layoutWidget)
        self.currentProjectLable.setObjectName("currentProjectLable")
        self.gridLayout_4.addWidget(self.currentProjectLable, 0, 0, 1, 1)
        self.projectInfoTitleLabel = QtGui.QLabel(self.layoutWidget)
        self.projectInfoTitleLabel.setText("")
        self.projectInfoTitleLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.projectInfoTitleLabel.setObjectName("projectInfoTitleLabel")
        self.gridLayout_4.addWidget(self.projectInfoTitleLabel, 1, 1, 1, 1)
        self.projectTitleLabel = QtGui.QLabel(self.layoutWidget)
        self.projectTitleLabel.setObjectName("projectTitleLabel")
        self.gridLayout_4.addWidget(self.projectTitleLabel, 1, 0, 1, 1)
        self.getProjectsButton = QtGui.QPushButton(self.layoutWidget)
        self.getProjectsButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.getProjectsButton.setObjectName("getProjectsButton")
        self.gridLayout_4.addWidget(self.getProjectsButton, 0, 2, 1, 1)
        self.currentProjectComboBox = QtGui.QComboBox(self.layoutWidget)
        self.currentProjectComboBox.setObjectName("currentProjectComboBox")
        self.gridLayout_4.addWidget(self.currentProjectComboBox, 0, 1, 1, 1)
        self.projectStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.projectStatusLabel.setObjectName("projectStatusLabel")
        self.gridLayout_4.addWidget(self.projectStatusLabel, 3, 0, 1, 1)
        self.projectUpdateLabel = QtGui.QLabel(self.layoutWidget)
        self.projectUpdateLabel.setObjectName("projectUpdateLabel")
        self.gridLayout_4.addWidget(self.projectUpdateLabel, 4, 0, 1, 1)
        self.projectInfoStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.projectInfoStatusLabel.setText("")
        self.projectInfoStatusLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.projectInfoStatusLabel.setObjectName("projectInfoStatusLabel")
        self.gridLayout_4.addWidget(self.projectInfoStatusLabel, 3, 1, 1, 1)
        self.projectInfoLastUpdLabel = QtGui.QLabel(self.layoutWidget)
        self.projectInfoLastUpdLabel.setText("")
        self.projectInfoLastUpdLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.projectInfoLastUpdLabel.setObjectName("projectInfoLastUpdLabel")
        self.gridLayout_4.addWidget(self.projectInfoLastUpdLabel, 4, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 5, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 5, 2, 1, 1)
        self.processTreeWidget_2 = QtGui.QTreeWidget(configuration_dialog)
        self.processTreeWidget_2.setGeometry(QtCore.QRect(520, 110, 439, 282))
        self.processTreeWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.processTreeWidget_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.processTreeWidget_2.setObjectName("processTreeWidget_2")
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget_2)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget_2)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget_2)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0 = QtGui.QTreeWidgetItem(self.processTreeWidget_2)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        self.processTreeWidget_2.header().setDefaultSectionSize(170)

        self.retranslateUi(configuration_dialog)
        self.configToolBox.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(configuration_dialog)
        configuration_dialog.setTabOrder(self.userNameLineEdit, self.passwordLineEdit)
        configuration_dialog.setTabOrder(self.passwordLineEdit, self.generateTicketButton)
        configuration_dialog.setTabOrder(self.generateTicketButton, self.tacticEnvLineEdit)
        configuration_dialog.setTabOrder(self.tacticEnvLineEdit, self.tacticAssetDirLineEdit)
        configuration_dialog.setTabOrder(self.tacticAssetDirLineEdit, self.tacticInstallDirLineEdit)
        configuration_dialog.setTabOrder(self.tacticInstallDirLineEdit, self.buttonBox)
        configuration_dialog.setTabOrder(self.buttonBox, self.currentWorkdirLineEdit)

    def retranslateUi(self, configuration_dialog):
        configuration_dialog.setWindowTitle(QtGui.QApplication.translate("configuration_dialog", "TACTIC Handler configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.currentWorkdirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Current Workdir:", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.scenePage), QtGui.QApplication.translate("configuration_dialog", "Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticInstallDirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic Install dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticServerLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic server:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticAssetDirLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic assets dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticEnvLable.setText(QtGui.QApplication.translate("configuration_dialog", "Tactic database:", None, QtGui.QApplication.UnicodeUTF8))
        self.generateTicketButton.setText(QtGui.QApplication.translate("configuration_dialog", "Generate new Ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.loginStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLable.setText(QtGui.QApplication.translate("configuration_dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.userNameLable.setText(QtGui.QApplication.translate("configuration_dialog", "User Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.tacticStatusLable.setText(QtGui.QApplication.translate("configuration_dialog", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.connectToServerButton.setText(QtGui.QApplication.translate("configuration_dialog", "Try to connect", None, QtGui.QApplication.UnicodeUTF8))
        self.addTacticEnv.setText(QtGui.QApplication.translate("configuration_dialog", "Add Tactic environments to system", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.loginPage), QtGui.QApplication.translate("configuration_dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("configuration_dialog", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.projectPage), QtGui.QApplication.translate("configuration_dialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("configuration_dialog", "Display process:", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Names", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Codes", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.processTreeWidget.isSortingEnabled()
        self.processTreeWidget.setSortingEnabled(False)
        self.processTreeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("configuration_dialog", "Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("configuration_dialog", "Characters", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/chars", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("configuration_dialog", "Props", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(1).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/props", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("configuration_dialog", "Scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(2).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("configuration_dialog", "Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(3).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/sets", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(4).setText(0, QtGui.QApplication.translate("configuration_dialog", "Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(0).child(4).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("configuration_dialog", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(2).setText(0, QtGui.QApplication.translate("configuration_dialog", "Nuke", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.topLevelItem(3).setText(0, QtGui.QApplication.translate("configuration_dialog", "NotTyped", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget.setSortingEnabled(__sortingEnabled)
        self.configToolBox.setItemText(self.configToolBox.indexOf(self.checkinOutPage), QtGui.QApplication.translate("configuration_dialog", "Checking/checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.projectCodeLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Project Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.currentProjectLable.setText(QtGui.QApplication.translate("configuration_dialog", "Current Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectTitleLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Project Title: ", None, QtGui.QApplication.UnicodeUTF8))
        self.getProjectsButton.setText(QtGui.QApplication.translate("configuration_dialog", "Get", None, QtGui.QApplication.UnicodeUTF8))
        self.projectStatusLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Project Statis:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectUpdateLabel.setText(QtGui.QApplication.translate("configuration_dialog", "Project Last Update:", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("configuration_dialog", "Names", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.headerItem().setText(1, QtGui.QApplication.translate("configuration_dialog", "Codes", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.processTreeWidget_2.isSortingEnabled()
        self.processTreeWidget_2.setSortingEnabled(False)
        self.processTreeWidget_2.topLevelItem(0).setText(0, QtGui.QApplication.translate("configuration_dialog", "Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("configuration_dialog", "Characters", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(0).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/chars", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("configuration_dialog", "Props", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(1).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/props", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("configuration_dialog", "Scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(2).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("configuration_dialog", "Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(3).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/sets", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(4).setText(0, QtGui.QApplication.translate("configuration_dialog", "Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(0).child(4).setText(1, QtGui.QApplication.translate("configuration_dialog", "exam/shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(1).setText(0, QtGui.QApplication.translate("configuration_dialog", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(2).setText(0, QtGui.QApplication.translate("configuration_dialog", "Nuke", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.topLevelItem(3).setText(0, QtGui.QApplication.translate("configuration_dialog", "NotTyped", None, QtGui.QApplication.UnicodeUTF8))
        self.processTreeWidget_2.setSortingEnabled(__sortingEnabled)

