# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf\ui_checkinOptionsPage.ui'
#
# Created: Sat Oct  5 00:17:16 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_checkinOptionsPageWidget(object):
    def setupUi(self, checkinOptionsPageWidget):
        checkinOptionsPageWidget.setObjectName("checkinOptionsPageWidget")
        self.checkinPageWidgetLayout = QtGui.QVBoxLayout(checkinOptionsPageWidget)
        self.checkinPageWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.checkinPageWidgetLayout.setObjectName("checkinPageWidgetLayout")
        self.checkinMiscOptionsGroupBox = QtGui.QGroupBox(checkinOptionsPageWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.checkinMiscOptionsGroupBox.setFont(font)
        self.checkinMiscOptionsGroupBox.setFlat(True)
        self.checkinMiscOptionsGroupBox.setObjectName("checkinMiscOptionsGroupBox")
        self.checkinMiscOptionsLayout = QtGui.QGridLayout(self.checkinMiscOptionsGroupBox)
        self.checkinMiscOptionsLayout.setContentsMargins(10, 24, -1, 0)
        self.checkinMiscOptionsLayout.setObjectName("checkinMiscOptionsLayout")
        self.versionsSeparateCheckinCheckBox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.versionsSeparateCheckinCheckBox.setObjectName("versionsSeparateCheckinCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.versionsSeparateCheckinCheckBox, 4, 0, 1, 1)
        self.snapshotDescriptionLimitCheckBox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.snapshotDescriptionLimitCheckBox.setChecked(True)
        self.snapshotDescriptionLimitCheckBox.setObjectName("snapshotDescriptionLimitCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.snapshotDescriptionLimitCheckBox, 6, 0, 1, 1)
        self.snapshotDescriptionLimitSpinBox = QtGui.QSpinBox(self.checkinMiscOptionsGroupBox)
        self.snapshotDescriptionLimitSpinBox.setMinimum(20)
        self.snapshotDescriptionLimitSpinBox.setMaximum(50000)
        self.snapshotDescriptionLimitSpinBox.setSingleStep(5)
        self.snapshotDescriptionLimitSpinBox.setProperty("value", 80)
        self.snapshotDescriptionLimitSpinBox.setObjectName("snapshotDescriptionLimitSpinBox")
        self.checkinMiscOptionsLayout.addWidget(self.snapshotDescriptionLimitSpinBox, 6, 2, 1, 1)
        self.bottomVersionsRadioButton = QtGui.QRadioButton(self.checkinMiscOptionsGroupBox)
        self.bottomVersionsRadioButton.setObjectName("bottomVersionsRadioButton")
        self.checkinMiscOptionsLayout.addWidget(self.bottomVersionsRadioButton, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.checkinMiscOptionsGroupBox)
        self.label_2.setObjectName("label_2")
        self.checkinMiscOptionsLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.displayLimitSpinBox = QtGui.QSpinBox(self.checkinMiscOptionsGroupBox)
        self.displayLimitSpinBox.setMinimum(20)
        self.displayLimitSpinBox.setMaximum(500)
        self.displayLimitSpinBox.setSingleStep(5)
        self.displayLimitSpinBox.setObjectName("displayLimitSpinBox")
        self.checkinMiscOptionsLayout.addWidget(self.displayLimitSpinBox, 7, 2, 1, 1)
        self.rightVersionsRadioButton = QtGui.QRadioButton(self.checkinMiscOptionsGroupBox)
        self.rightVersionsRadioButton.setChecked(True)
        self.rightVersionsRadioButton.setObjectName("rightVersionsRadioButton")
        self.checkinMiscOptionsLayout.addWidget(self.rightVersionsRadioButton, 4, 2, 1, 1)
        self.doubleClickSaveCheckBox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.doubleClickSaveCheckBox.setObjectName("doubleClickSaveCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.doubleClickSaveCheckBox, 1, 0, 1, 3)
        self.doubleClickOpenCheckBox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.doubleClickOpenCheckBox.setObjectName("doubleClickOpenCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.doubleClickOpenCheckBox, 2, 0, 1, 3)
        self.showAllProcessCheckBox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.showAllProcessCheckBox.setObjectName("showAllProcessCheckBox")
        self.checkinMiscOptionsLayout.addWidget(self.showAllProcessCheckBox, 3, 0, 1, 3)
        self.getPreviewsThroughHttpCheckbox = QtGui.QCheckBox(self.checkinMiscOptionsGroupBox)
        self.getPreviewsThroughHttpCheckbox.setObjectName("getPreviewsThroughHttpCheckbox")
        self.checkinMiscOptionsLayout.addWidget(self.getPreviewsThroughHttpCheckbox, 0, 0, 1, 3)
        self.checkinMiscOptionsLayout.setColumnStretch(0, 1)
        self.checkinPageWidgetLayout.addWidget(self.checkinMiscOptionsGroupBox)
        self.snapshotsSavingOptionsGroupBox = QtGui.QGroupBox(checkinOptionsPageWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.snapshotsSavingOptionsGroupBox.setFont(font)
        self.snapshotsSavingOptionsGroupBox.setFlat(True)
        self.snapshotsSavingOptionsGroupBox.setObjectName("snapshotsSavingOptionsGroupBox")
        self.snapshotsSavingOptionsLayout = QtGui.QGridLayout(self.snapshotsSavingOptionsGroupBox)
        self.snapshotsSavingOptionsLayout.setContentsMargins(10, 24, -1, 0)
        self.snapshotsSavingOptionsLayout.setObjectName("snapshotsSavingOptionsLayout")
        self.repositoryComboBox = QtGui.QComboBox(self.snapshotsSavingOptionsGroupBox)
        self.repositoryComboBox.setObjectName("repositoryComboBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.repositoryComboBox, 1, 1, 1, 3)
        self.updateVersionlessCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.updateVersionlessCheckBox.setChecked(True)
        self.updateVersionlessCheckBox.setObjectName("updateVersionlessCheckBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.updateVersionlessCheckBox, 4, 0, 1, 1)
        self.seuqenceNamingHorizontalLayout = QtGui.QHBoxLayout()
        self.seuqenceNamingHorizontalLayout.setSpacing(4)
        self.seuqenceNamingHorizontalLayout.setObjectName("seuqenceNamingHorizontalLayout")
        self.sequenceNamingTemplateLineEdit = QtGui.QLineEdit(self.snapshotsSavingOptionsGroupBox)
        self.sequenceNamingTemplateLineEdit.setReadOnly(True)
        self.sequenceNamingTemplateLineEdit.setObjectName("sequenceNamingTemplateLineEdit")
        self.seuqenceNamingHorizontalLayout.addWidget(self.sequenceNamingTemplateLineEdit)
        self.editSequenceNamingTemplateToolButton = QtGui.QToolButton(self.snapshotsSavingOptionsGroupBox)
        self.editSequenceNamingTemplateToolButton.setText("")
        self.editSequenceNamingTemplateToolButton.setAutoRaise(True)
        self.editSequenceNamingTemplateToolButton.setObjectName("editSequenceNamingTemplateToolButton")
        self.seuqenceNamingHorizontalLayout.addWidget(self.editSequenceNamingTemplateToolButton)
        self.seuqenceNamingHorizontalLayout.setStretch(0, 1)
        self.snapshotsSavingOptionsLayout.addLayout(self.seuqenceNamingHorizontalLayout, 11, 1, 1, 3)
        self.sequencePaddingHorizontalLayout = QtGui.QHBoxLayout()
        self.sequencePaddingHorizontalLayout.setSpacing(4)
        self.sequencePaddingHorizontalLayout.setObjectName("sequencePaddingHorizontalLayout")
        self.sequencePaddingHorizontalSlider = QtGui.QSlider(self.snapshotsSavingOptionsGroupBox)
        self.sequencePaddingHorizontalSlider.setMinimum(1)
        self.sequencePaddingHorizontalSlider.setMaximum(9)
        self.sequencePaddingHorizontalSlider.setProperty("value", 3)
        self.sequencePaddingHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sequencePaddingHorizontalSlider.setObjectName("sequencePaddingHorizontalSlider")
        self.sequencePaddingHorizontalLayout.addWidget(self.sequencePaddingHorizontalSlider)
        self.sequencePaddingSpinBox = QtGui.QSpinBox(self.snapshotsSavingOptionsGroupBox)
        self.sequencePaddingSpinBox.setMinimum(1)
        self.sequencePaddingSpinBox.setMaximum(9)
        self.sequencePaddingSpinBox.setProperty("value", 3)
        self.sequencePaddingSpinBox.setObjectName("sequencePaddingSpinBox")
        self.sequencePaddingHorizontalLayout.addWidget(self.sequencePaddingSpinBox)
        self.sequencePaddingHorizontalLayout.setStretch(0, 1)
        self.snapshotsSavingOptionsLayout.addLayout(self.sequencePaddingHorizontalLayout, 10, 1, 1, 3)
        self.createPlayblastCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.createPlayblastCheckBox.setChecked(True)
        self.createPlayblastCheckBox.setObjectName("createPlayblastCheckBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.createPlayblastCheckBox, 7, 0, 1, 1)
        self.confirmsHorizontalLayout = QtGui.QHBoxLayout()
        self.confirmsHorizontalLayout.setSpacing(0)
        self.confirmsHorizontalLayout.setObjectName("confirmsHorizontalLayout")
        self.askBeforeSaveCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.askBeforeSaveCheckBox.setChecked(True)
        self.askBeforeSaveCheckBox.setObjectName("askBeforeSaveCheckBox")
        self.confirmsHorizontalLayout.addWidget(self.askBeforeSaveCheckBox)
        self.askReplaceRevisionCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.askReplaceRevisionCheckBox.setChecked(True)
        self.askReplaceRevisionCheckBox.setObjectName("askReplaceRevisionCheckBox")
        self.confirmsHorizontalLayout.addWidget(self.askReplaceRevisionCheckBox)
        self.snapshotsSavingOptionsLayout.addLayout(self.confirmsHorizontalLayout, 8, 0, 1, 4)
        self.createMayaDirsCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.createMayaDirsCheckBox.setObjectName("createMayaDirsCheckBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.createMayaDirsCheckBox, 6, 0, 1, 1)
        self.generatePreviewsCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.generatePreviewsCheckBox.setChecked(True)
        self.generatePreviewsCheckBox.setObjectName("generatePreviewsCheckBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.generatePreviewsCheckBox, 5, 0, 1, 1)
        self.sequencePaddingCheckBox = QtGui.QCheckBox(self.snapshotsSavingOptionsGroupBox)
        self.sequencePaddingCheckBox.setObjectName("sequencePaddingCheckBox")
        self.snapshotsSavingOptionsLayout.addWidget(self.sequencePaddingCheckBox, 10, 0, 1, 1)
        self.checkinMethodLabel = QtGui.QLabel(self.snapshotsSavingOptionsGroupBox)
        self.checkinMethodLabel.setObjectName("checkinMethodLabel")
        self.snapshotsSavingOptionsLayout.addWidget(self.checkinMethodLabel, 2, 0, 1, 1)
        self.checkinMethodComboBox = QtGui.QComboBox(self.snapshotsSavingOptionsGroupBox)
        self.checkinMethodComboBox.setObjectName("checkinMethodComboBox")
        self.checkinMethodComboBox.addItem("")
        self.checkinMethodComboBox.addItem("")
        self.checkinMethodComboBox.addItem("")
        self.checkinMethodComboBox.addItem("")
        self.checkinMethodComboBox.addItem("")
        self.snapshotsSavingOptionsLayout.addWidget(self.checkinMethodComboBox, 2, 1, 1, 3)
        self.repositoryLabel = QtGui.QLabel(self.snapshotsSavingOptionsGroupBox)
        self.repositoryLabel.setObjectName("repositoryLabel")
        self.snapshotsSavingOptionsLayout.addWidget(self.repositoryLabel, 1, 0, 1, 1)
        self.sequqnceNamingTemplatelabel = QtGui.QLabel(self.snapshotsSavingOptionsGroupBox)
        self.sequqnceNamingTemplatelabel.setObjectName("sequqnceNamingTemplatelabel")
        self.snapshotsSavingOptionsLayout.addWidget(self.sequqnceNamingTemplatelabel, 11, 0, 1, 1)
        self.checkoutMethodLabel = QtGui.QLabel(self.snapshotsSavingOptionsGroupBox)
        self.checkoutMethodLabel.setObjectName("checkoutMethodLabel")
        self.snapshotsSavingOptionsLayout.addWidget(self.checkoutMethodLabel, 3, 0, 1, 1)
        self.checkoutMethodComboBox = QtGui.QComboBox(self.snapshotsSavingOptionsGroupBox)
        self.checkoutMethodComboBox.setObjectName("checkoutMethodComboBox")
        self.checkoutMethodComboBox.addItem("")
        self.checkoutMethodComboBox.addItem("")
        self.snapshotsSavingOptionsLayout.addWidget(self.checkoutMethodComboBox, 3, 1, 1, 3)
        self.checkinPageWidgetLayout.addWidget(self.snapshotsSavingOptionsGroupBox)
        self.dropPlateOptionsGroupBox = QtGui.QGroupBox(checkinOptionsPageWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.dropPlateOptionsGroupBox.setFont(font)
        self.dropPlateOptionsGroupBox.setFlat(True)
        self.dropPlateOptionsGroupBox.setObjectName("dropPlateOptionsGroupBox")
        self.dropPlateOptionsLayout = QtGui.QGridLayout(self.dropPlateOptionsGroupBox)
        self.dropPlateOptionsLayout.setContentsMargins(10, 24, -1, 0)
        self.dropPlateOptionsLayout.setObjectName("dropPlateOptionsLayout")
        self.horizontalSlider = QtGui.QSlider(self.dropPlateOptionsGroupBox)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(9)
        self.horizontalSlider.setProperty("value", 3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.dropPlateOptionsLayout.addWidget(self.horizontalSlider, 5, 1, 1, 1)
        self.minFramesPaddingSpinBox = QtGui.QSpinBox(self.dropPlateOptionsGroupBox)
        self.minFramesPaddingSpinBox.setMinimum(1)
        self.minFramesPaddingSpinBox.setMaximum(9)
        self.minFramesPaddingSpinBox.setProperty("value", 3)
        self.minFramesPaddingSpinBox.setObjectName("minFramesPaddingSpinBox")
        self.dropPlateOptionsLayout.addWidget(self.minFramesPaddingSpinBox, 5, 2, 1, 1)
        self.label = QtGui.QLabel(self.dropPlateOptionsGroupBox)
        self.label.setObjectName("label")
        self.dropPlateOptionsLayout.addWidget(self.label, 5, 0, 1, 1)
        self.uncheckFromDropPlateCheckBox = QtGui.QCheckBox(self.dropPlateOptionsGroupBox)
        self.uncheckFromDropPlateCheckBox.setChecked(True)
        self.uncheckFromDropPlateCheckBox.setObjectName("uncheckFromDropPlateCheckBox")
        self.dropPlateOptionsLayout.addWidget(self.uncheckFromDropPlateCheckBox, 1, 0, 1, 1)
        self.clearDropPlateAfterCheckincheckBox = QtGui.QCheckBox(self.dropPlateOptionsGroupBox)
        self.clearDropPlateAfterCheckincheckBox.setChecked(True)
        self.clearDropPlateAfterCheckincheckBox.setObjectName("clearDropPlateAfterCheckincheckBox")
        self.dropPlateOptionsLayout.addWidget(self.clearDropPlateAfterCheckincheckBox, 2, 0, 1, 1)
        self.oneFrameSequenceDetectionCheckBox = QtGui.QCheckBox(self.dropPlateOptionsGroupBox)
        self.oneFrameSequenceDetectionCheckBox.setChecked(True)
        self.oneFrameSequenceDetectionCheckBox.setObjectName("oneFrameSequenceDetectionCheckBox")
        self.dropPlateOptionsLayout.addWidget(self.oneFrameSequenceDetectionCheckBox, 4, 1, 1, 2)
        self.oneUdimDetectionCheckBox = QtGui.QCheckBox(self.dropPlateOptionsGroupBox)
        self.oneUdimDetectionCheckBox.setChecked(True)
        self.oneUdimDetectionCheckBox.setObjectName("oneUdimDetectionCheckBox")
        self.dropPlateOptionsLayout.addWidget(self.oneUdimDetectionCheckBox, 4, 0, 1, 1)
        self.syckDropPlateCheckBox = QtGui.QCheckBox(self.dropPlateOptionsGroupBox)
        self.syckDropPlateCheckBox.setChecked(True)
        self.syckDropPlateCheckBox.setObjectName("syckDropPlateCheckBox")
        self.dropPlateOptionsLayout.addWidget(self.syckDropPlateCheckBox, 0, 0, 1, 1)
        self.checkinPageWidgetLayout.addWidget(self.dropPlateOptionsGroupBox)
        self.defaultRepoPathsGroupBox = QtGui.QGroupBox(checkinOptionsPageWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.defaultRepoPathsGroupBox.setFont(font)
        self.defaultRepoPathsGroupBox.setFlat(True)
        self.defaultRepoPathsGroupBox.setObjectName("defaultRepoPathsGroupBox")
        self.defaultRepoPathsLayout = QtGui.QGridLayout(self.defaultRepoPathsGroupBox)
        self.defaultRepoPathsLayout.setContentsMargins(10, 24, -1, 0)
        self.defaultRepoPathsLayout.setObjectName("defaultRepoPathsLayout")
        self.handoffCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.handoffCheckBox.setObjectName("handoffCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.handoffCheckBox, 5, 0, 1, 1)
        self.clientRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirNameLineEdit.setObjectName("clientRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirNameLineEdit, 4, 2, 1, 1)
        self.sandboxDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirPathLineEdit.setObjectName("sandboxDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirPathLineEdit, 2, 3, 1, 1)
        self.sandboxDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.sandboxDirNameLineEdit.setObjectName("sandboxDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirNameLineEdit, 2, 2, 1, 1)
        self.localRepoDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirNameLineEdit.setObjectName("localRepoDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirNameLineEdit, 3, 2, 1, 1)
        self.clientRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.clientRepoCheckBox.setObjectName("clientRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoCheckBox, 4, 0, 1, 1)
        self.localRepoCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.localRepoCheckBox.setChecked(True)
        self.localRepoCheckBox.setObjectName("localRepoCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.localRepoCheckBox, 3, 0, 1, 1)
        self.handoffDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.handoffDirPathLineEdit.setObjectName("handoffDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.handoffDirPathLineEdit, 5, 2, 1, 2)
        self.assetBaseDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.assetBaseDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.assetBaseDirColorToolButton.setStyleSheet("QToolButton {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    border-radius: 4px;\n"
"    background-color:  rgb(96, 96, 96);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}")
        self.assetBaseDirColorToolButton.setChecked(False)
        self.assetBaseDirColorToolButton.setObjectName("assetBaseDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirColorToolButton, 1, 1, 1, 1)
        self.sandboxCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.sandboxCheckBox.setObjectName("sandboxCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.sandboxCheckBox, 2, 0, 1, 1)
        self.localRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.localRepoDirPathLineEdit.setObjectName("localRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirPathLineEdit, 3, 3, 1, 1)
        self.sandboxDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.sandboxDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.sandboxDirColorToolButton.setStyleSheet("QToolButton {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    border-radius: 4px;\n"
"    background-color:  rgb(128, 64, 64);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(108, 44, 44);\n"
"}")
        self.sandboxDirColorToolButton.setChecked(False)
        self.sandboxDirColorToolButton.setObjectName("sandboxDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.sandboxDirColorToolButton, 2, 1, 1, 1)
        self.clientRepoDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.clientRepoDirPathLineEdit.setObjectName("clientRepoDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirPathLineEdit, 4, 3, 1, 1)
        self.clientRepoDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.clientRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.clientRepoDirColorToolButton.setStyleSheet("QToolButton {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    border-radius: 4px;\n"
"    background-color:  rgb(31, 143, 0);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(11, 123, 0);\n"
"}")
        self.clientRepoDirColorToolButton.setChecked(False)
        self.clientRepoDirColorToolButton.setObjectName("clientRepoDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.clientRepoDirColorToolButton, 4, 1, 1, 1)
        self.localRepoDirColorToolButton = QtGui.QToolButton(self.defaultRepoPathsGroupBox)
        self.localRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.localRepoDirColorToolButton.setStyleSheet("QToolButton {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    border-radius: 4px;\n"
"    background-color:  rgb(255, 140, 40);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(235, 120, 20);\n"
"}")
        self.localRepoDirColorToolButton.setChecked(False)
        self.localRepoDirColorToolButton.setObjectName("localRepoDirColorToolButton")
        self.defaultRepoPathsLayout.addWidget(self.localRepoDirColorToolButton, 3, 1, 1, 1)
        self.assetBaseDirCheckBox = QtGui.QCheckBox(self.defaultRepoPathsGroupBox)
        self.assetBaseDirCheckBox.setChecked(True)
        self.assetBaseDirCheckBox.setObjectName("assetBaseDirCheckBox")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirCheckBox, 0, 0, 2, 1)
        self.assetBaseDirNameLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirNameLineEdit.setObjectName("assetBaseDirNameLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirNameLineEdit, 0, 2, 2, 1)
        self.assetBaseDirPathLineEdit = QtGui.QLineEdit(self.defaultRepoPathsGroupBox)
        self.assetBaseDirPathLineEdit.setObjectName("assetBaseDirPathLineEdit")
        self.defaultRepoPathsLayout.addWidget(self.assetBaseDirPathLineEdit, 0, 3, 2, 1)
        self.defaultRepoPathsLayout.setColumnStretch(3, 1)
        self.checkinPageWidgetLayout.addWidget(self.defaultRepoPathsGroupBox)
        self.customRepoPathsGroupBox = QtGui.QGroupBox(checkinOptionsPageWidget)
        self.customRepoPathsGroupBox.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.customRepoPathsGroupBox.setFont(font)
        self.customRepoPathsGroupBox.setFlat(True)
        self.customRepoPathsGroupBox.setCheckable(True)
        self.customRepoPathsGroupBox.setChecked(False)
        self.customRepoPathsGroupBox.setObjectName("customRepoPathsGroupBox")
        self.customRepoPathsLayout = QtGui.QGridLayout(self.customRepoPathsGroupBox)
        self.customRepoPathsLayout.setContentsMargins(10, 24, -1, 0)
        self.customRepoPathsLayout.setObjectName("customRepoPathsLayout")
        self.label_7 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_7.setObjectName("label_7")
        self.customRepoPathsLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.customRepoDirColorToolButton = QtGui.QToolButton(self.customRepoPathsGroupBox)
        self.customRepoDirColorToolButton.setMaximumSize(QtCore.QSize(20, 20))
        self.customRepoDirColorToolButton.setStyleSheet("QToolButton {\n"
"    border: 1px solid rgb(128, 128, 128);\n"
"    border-radius: 4px;\n"
"    background-color:  rgb(64, 64, 64);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(44, 44, 44);\n"
"}")
        self.customRepoDirColorToolButton.setChecked(False)
        self.customRepoDirColorToolButton.setObjectName("customRepoDirColorToolButton")
        self.customRepoPathsLayout.addWidget(self.customRepoDirColorToolButton, 0, 1, 1, 1)
        self.customRepoDirNameLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirNameLineEdit.setObjectName("customRepoDirNameLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirNameLineEdit, 0, 2, 1, 3)
        self.label_8 = QtGui.QLabel(self.customRepoPathsGroupBox)
        self.label_8.setObjectName("label_8")
        self.customRepoPathsLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.customRepoDirPathLineEdit = QtGui.QLineEdit(self.customRepoPathsGroupBox)
        self.customRepoDirPathLineEdit.setObjectName("customRepoDirPathLineEdit")
        self.customRepoPathsLayout.addWidget(self.customRepoDirPathLineEdit, 1, 1, 1, 4)
        self.customRepoComboBox = QtGui.QComboBox(self.customRepoPathsGroupBox)
        self.customRepoComboBox.setObjectName("customRepoComboBox")
        self.customRepoPathsLayout.addWidget(self.customRepoComboBox, 2, 0, 1, 1)
        self.addCustomRepoToListPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.addCustomRepoToListPushButton.setObjectName("addCustomRepoToListPushButton")
        self.customRepoPathsLayout.addWidget(self.addCustomRepoToListPushButton, 2, 1, 1, 2)
        self.editCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.editCustomRepoPushButton.setObjectName("editCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.editCustomRepoPushButton, 2, 3, 1, 1)
        self.deleteCustomRepoPushButton = QtGui.QPushButton(self.customRepoPathsGroupBox)
        self.deleteCustomRepoPushButton.setObjectName("deleteCustomRepoPushButton")
        self.customRepoPathsLayout.addWidget(self.deleteCustomRepoPushButton, 2, 4, 1, 1)
        self.customRepoTreeWidget = QtGui.QTreeWidget(self.customRepoPathsGroupBox)
        self.customRepoTreeWidget.setStyleSheet("QTreeView::item {\n"
"    padding: 2px;\n"
"}")
        self.customRepoTreeWidget.setIndentation(0)
        self.customRepoTreeWidget.setRootIsDecorated(False)
        self.customRepoTreeWidget.setObjectName("customRepoTreeWidget")
        self.customRepoPathsLayout.addWidget(self.customRepoTreeWidget, 3, 0, 1, 5)
        self.checkinPageWidgetLayout.addWidget(self.customRepoPathsGroupBox)

        self.retranslateUi(checkinOptionsPageWidget)
        QtCore.QObject.connect(self.sequencePaddingHorizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.sequencePaddingSpinBox.setValue)
        QtCore.QObject.connect(self.sequencePaddingSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.sequencePaddingHorizontalSlider.setValue)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.minFramesPaddingSpinBox.setValue)
        QtCore.QObject.connect(self.minFramesPaddingSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(checkinOptionsPageWidget)

    def retranslateUi(self, checkinOptionsPageWidget):
        self.checkinMiscOptionsGroupBox.setTitle(QtGui.QApplication.translate("checkinOptionsPageWidget", "Search Results Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.versionsSeparateCheckinCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Display Versions separated:", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotDescriptionLimitCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Limit snapshot description preview (symbols):", None, QtGui.QApplication.UnicodeUTF8))
        self.bottomVersionsRadioButton.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Search results limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.rightVersionsRadioButton.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickSaveCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "DoubleClick for Save", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleClickOpenCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Shift + DoubleClick for Open", None, QtGui.QApplication.UnicodeUTF8))
        self.showAllProcessCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Show Builtin Processes (publish, icon, attachement)", None, QtGui.QApplication.UnicodeUTF8))
        self.getPreviewsThroughHttpCheckbox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Get Previews Though HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotsSavingOptionsGroupBox.setTitle(QtGui.QApplication.translate("checkinOptionsPageWidget", "Snapshots Saving Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.updateVersionlessCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Update versionless snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.sequenceNamingTemplateLineEdit.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "$FILENAME_$LAYER_$UDIM/UV.$FRAME.$EXT", None, QtGui.QApplication.UnicodeUTF8))
        self.createPlayblastCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Create screenshot (playblast)", None, QtGui.QApplication.UnicodeUTF8))
        self.askBeforeSaveCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Confirm Saving", None, QtGui.QApplication.UnicodeUTF8))
        self.askReplaceRevisionCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Revision Confirm Saving", None, QtGui.QApplication.UnicodeUTF8))
        self.createMayaDirsCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Create Maya Dirs (worspace.mel)", None, QtGui.QApplication.UnicodeUTF8))
        self.generatePreviewsCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Generate Previews", None, QtGui.QApplication.UnicodeUTF8))
        self.sequencePaddingCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Sequence Padding:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodLabel.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Checkin Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodComboBox.setItemText(0, QtGui.QApplication.translate("checkinOptionsPageWidget", "Preallocate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodComboBox.setItemText(1, QtGui.QApplication.translate("checkinOptionsPageWidget", "In-Place", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodComboBox.setItemText(2, QtGui.QApplication.translate("checkinOptionsPageWidget", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodComboBox.setItemText(3, QtGui.QApplication.translate("checkinOptionsPageWidget", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.checkinMethodComboBox.setItemText(4, QtGui.QApplication.translate("checkinOptionsPageWidget", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.repositoryLabel.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Current Repository:", None, QtGui.QApplication.UnicodeUTF8))
        self.sequqnceNamingTemplatelabel.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Sequence, udim/uv naming Template:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkoutMethodLabel.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Checkout Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkoutMethodComboBox.setItemText(0, QtGui.QApplication.translate("checkinOptionsPageWidget", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.checkoutMethodComboBox.setItemText(1, QtGui.QApplication.translate("checkinOptionsPageWidget", "HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.dropPlateOptionsGroupBox.setTitle(QtGui.QApplication.translate("checkinOptionsPageWidget", "Drop Plate Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Minimum Frames padding: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uncheckFromDropPlateCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Uncheck \"From DropPlate\" after Checkin", None, QtGui.QApplication.UnicodeUTF8))
        self.clearDropPlateAfterCheckincheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Clear DropPlate after Checkin", None, QtGui.QApplication.UnicodeUTF8))
        self.oneFrameSequenceDetectionCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Allow Single Frame Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.oneUdimDetectionCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Allow single UDIM/UV", None, QtGui.QApplication.UnicodeUTF8))
        self.syckDropPlateCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Sync Drop Plate to All Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("checkinOptionsPageWidget", "Repository Paths:", None, QtGui.QApplication.UnicodeUTF8))
        self.handoffCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Use handoff dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientRepoCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Client repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.localRepoCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Local repo dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.sandboxCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Sandbox dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.assetBaseDirCheckBox.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Asset base dir:", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoPathsGroupBox.setTitle(QtGui.QApplication.translate("checkinOptionsPageWidget", "Custom Repository Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Custom Repo name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Repo path:", None, QtGui.QApplication.UnicodeUTF8))
        self.addCustomRepoToListPushButton.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editCustomRepoPushButton.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCustomRepoPushButton.setText(QtGui.QApplication.translate("checkinOptionsPageWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("checkinOptionsPageWidget", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(1, QtGui.QApplication.translate("checkinOptionsPageWidget", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(2, QtGui.QApplication.translate("checkinOptionsPageWidget", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.customRepoTreeWidget.headerItem().setText(3, QtGui.QApplication.translate("checkinOptionsPageWidget", "Path", None, QtGui.QApplication.UnicodeUTF8))

