# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf/ui_serverPage.ui'
#
# Created: Mon May  7 15:40:19 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from thlib.side.Qt import QtWidgets as QtGui
from thlib.side.Qt import QtGui as Qt4Gui
from thlib.side.Qt import QtCore

class Ui_serverPageWidget(object):
    def setupUi(self, serverPageWidget):
        serverPageWidget.setObjectName("serverPageWidget")
        self.serverPageWidgetLayout = QtGui.QVBoxLayout(serverPageWidget)
        self.serverPageWidgetLayout.setSpacing(6)
        self.serverPageWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.serverPageWidgetLayout.setObjectName("serverPageWidgetLayout")
        self.authorizingGroupBox = QtGui.QGroupBox(serverPageWidget)
        font = Qt4Gui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.authorizingGroupBox.setFont(font)
        self.authorizingGroupBox.setFlat(True)
        self.authorizingGroupBox.setObjectName("authorizingGroupBox")
        self.authorizationLayout = QtGui.QGridLayout(self.authorizingGroupBox)
        self.authorizationLayout.setContentsMargins(10, 24, 9, 0)
        self.authorizationLayout.setObjectName("authorizationLayout")
        self.userNameLable = QtGui.QLabel(self.authorizingGroupBox)
        self.userNameLable.setMinimumSize(QtCore.QSize(120, 0))
        self.userNameLable.setObjectName("userNameLable")
        self.authorizationLayout.addWidget(self.userNameLable, 2, 0, 1, 1)
        self.tacticServerLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticServerLable.setObjectName("tacticServerLable")
        self.authorizationLayout.addWidget(self.tacticServerLable, 3, 0, 1, 1)
        self.usePortalSiteCheckBox = QtGui.QCheckBox(self.authorizingGroupBox)
        self.usePortalSiteCheckBox.setObjectName("usePortalSiteCheckBox")
        self.authorizationLayout.addWidget(self.usePortalSiteCheckBox, 4, 0, 1, 1)
        self.savedServerPresetLabel = QtGui.QLabel(self.authorizingGroupBox)
        self.savedServerPresetLabel.setObjectName("savedServerPresetLabel")
        self.authorizationLayout.addWidget(self.savedServerPresetLabel, 1, 0, 1, 1)
        self.userNameLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.userNameLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.authorizationLayout.addWidget(self.userNameLineEdit, 2, 1, 1, 2)
        self.tacticServerLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.tacticServerLineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.tacticServerLineEdit.setObjectName("tacticServerLineEdit")
        self.authorizationLayout.addWidget(self.tacticServerLineEdit, 3, 1, 1, 2)
        self.serverPresetsComboBox = QtGui.QComboBox(self.authorizingGroupBox)
        self.serverPresetsComboBox.setObjectName("serverPresetsComboBox")
        self.authorizationLayout.addWidget(self.serverPresetsComboBox, 1, 1, 1, 2)
        self.editServerPresetsPushButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.editServerPresetsPushButton.setObjectName("editServerPresetsPushButton")
        self.authorizationLayout.addWidget(self.editServerPresetsPushButton, 1, 3, 1, 1)
        self.generateTicketButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.generateTicketButton.setObjectName("generateTicketButton")
        self.authorizationLayout.addWidget(self.generateTicketButton, 2, 3, 1, 1)
        self.siteLineEdit = QtGui.QLineEdit(self.authorizingGroupBox)
        self.siteLineEdit.setEnabled(False)
        self.siteLineEdit.setObjectName("siteLineEdit")
        self.authorizationLayout.addWidget(self.siteLineEdit, 4, 1, 1, 3)
        self.connectToServerButton = QtGui.QPushButton(self.authorizingGroupBox)
        self.connectToServerButton.setMinimumSize(QtCore.QSize(120, 0))
        self.connectToServerButton.setObjectName("connectToServerButton")
        self.authorizationLayout.addWidget(self.connectToServerButton, 3, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tacticStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.tacticStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.tacticStatusLable.setObjectName("tacticStatusLable")
        self.horizontalLayout_2.addWidget(self.tacticStatusLable)
        self.loginStatusLable = QtGui.QLabel(self.authorizingGroupBox)
        self.loginStatusLable.setMinimumSize(QtCore.QSize(90, 0))
        self.loginStatusLable.setObjectName("loginStatusLable")
        self.horizontalLayout_2.addWidget(self.loginStatusLable)
        self.authorizationLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 4)
        self.authorizationLayout.setColumnStretch(1, 1)
        self.serverPageWidgetLayout.addWidget(self.authorizingGroupBox)
        self.proxyGroupBox = QtGui.QGroupBox(serverPageWidget)
        font = Qt4Gui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.proxyGroupBox.setFont(font)
        self.proxyGroupBox.setFlat(True)
        self.proxyGroupBox.setCheckable(True)
        self.proxyGroupBox.setChecked(False)
        self.proxyGroupBox.setObjectName("proxyGroupBox")
        self.proxyGridLayout = QtGui.QGridLayout(self.proxyGroupBox)
        self.proxyGridLayout.setContentsMargins(10, 24, 9, 0)
        self.proxyGridLayout.setObjectName("proxyGridLayout")
        self.proxyUserNameLabel = QtGui.QLabel(self.proxyGroupBox)
        self.proxyUserNameLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.proxyUserNameLabel.setObjectName("proxyUserNameLabel")
        self.proxyGridLayout.addWidget(self.proxyUserNameLabel, 0, 0, 1, 1)
        self.proxyPasswordLabel = QtGui.QLabel(self.proxyGroupBox)
        self.proxyPasswordLabel.setObjectName("proxyPasswordLabel")
        self.proxyGridLayout.addWidget(self.proxyPasswordLabel, 1, 0, 1, 1)
        self.proxyServerLabel = QtGui.QLabel(self.proxyGroupBox)
        self.proxyServerLabel.setObjectName("proxyServerLabel")
        self.proxyGridLayout.addWidget(self.proxyServerLabel, 2, 0, 1, 1)
        self.proxyLoginLineEdit = QtGui.QLineEdit(self.proxyGroupBox)
        self.proxyLoginLineEdit.setObjectName("proxyLoginLineEdit")
        self.proxyGridLayout.addWidget(self.proxyLoginLineEdit, 0, 1, 1, 1)
        self.proxyPasswordLineEdit = QtGui.QLineEdit(self.proxyGroupBox)
        self.proxyPasswordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.proxyPasswordLineEdit.setObjectName("proxyPasswordLineEdit")
        self.proxyGridLayout.addWidget(self.proxyPasswordLineEdit, 1, 1, 1, 1)
        self.proxyServerLineEdit = QtGui.QLineEdit(self.proxyGroupBox)
        self.proxyServerLineEdit.setObjectName("proxyServerLineEdit")
        self.proxyGridLayout.addWidget(self.proxyServerLineEdit, 2, 1, 1, 1)
        self.serverPageWidgetLayout.addWidget(self.proxyGroupBox)
        self.environmentsGroupBox = QtGui.QGroupBox(serverPageWidget)
        self.environmentsGroupBox.setEnabled(False)
        font = Qt4Gui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.environmentsGroupBox.setFont(font)
        self.environmentsGroupBox.setFlat(True)
        self.environmentsGroupBox.setObjectName("environmentsGroupBox")
        self.environmentLayout = QtGui.QGridLayout(self.environmentsGroupBox)
        self.environmentLayout.setContentsMargins(10, 24, 9, 0)
        self.environmentLayout.setObjectName("environmentLayout")
        self.tacticEnvLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticEnvLable.setMinimumSize(QtCore.QSize(120, 0))
        self.tacticEnvLable.setObjectName("tacticEnvLable")
        self.environmentLayout.addWidget(self.tacticEnvLable, 0, 0, 1, 1)
        self.tacticEnvLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticEnvLineEdit.setObjectName("tacticEnvLineEdit")
        self.environmentLayout.addWidget(self.tacticEnvLineEdit, 0, 1, 1, 1)
        self.tacticInstallDirLable = QtGui.QLabel(self.environmentsGroupBox)
        self.tacticInstallDirLable.setObjectName("tacticInstallDirLable")
        self.environmentLayout.addWidget(self.tacticInstallDirLable, 1, 0, 1, 1)
        self.tacticInstallDirLineEdit = QtGui.QLineEdit(self.environmentsGroupBox)
        self.tacticInstallDirLineEdit.setObjectName("tacticInstallDirLineEdit")
        self.environmentLayout.addWidget(self.tacticInstallDirLineEdit, 1, 1, 1, 1)
        self.addTacticEnv = QtGui.QPushButton(self.environmentsGroupBox)
        self.addTacticEnv.setObjectName("addTacticEnv")
        self.environmentLayout.addWidget(self.addTacticEnv, 2, 0, 1, 2)
        self.serverPageWidgetLayout.addWidget(self.environmentsGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 58, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.serverPageWidgetLayout.addItem(spacerItem)

        self.retranslateUi(serverPageWidget)
        QtCore.QObject.connect(self.usePortalSiteCheckBox, QtCore.SIGNAL("toggled(bool)"), self.siteLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(serverPageWidget)

    def retranslateUi(self, serverPageWidget):
        self.authorizingGroupBox.setTitle(QtGui.QApplication.translate("serverPageWidget", "Authorization:", None))
        self.userNameLable.setText(QtGui.QApplication.translate("serverPageWidget", "User Name:", None))
        self.tacticServerLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic server:", None))
        self.usePortalSiteCheckBox.setText(QtGui.QApplication.translate("serverPageWidget", "Use Portal Site", None))
        self.savedServerPresetLabel.setText(QtGui.QApplication.translate("serverPageWidget", "Server presets:", None))
        self.editServerPresetsPushButton.setText(QtGui.QApplication.translate("serverPageWidget", "Edit Server Presets", None))
        self.generateTicketButton.setText(QtGui.QApplication.translate("serverPageWidget", "Generate New Ticket", None))
        self.connectToServerButton.setText(QtGui.QApplication.translate("serverPageWidget", "Check Connection", None))
        self.tacticStatusLable.setText(QtGui.QApplication.translate("serverPageWidget", "Connection Status:", None))
        self.loginStatusLable.setText(QtGui.QApplication.translate("serverPageWidget", "Ticket Status:", None))
        self.proxyGroupBox.setTitle(QtGui.QApplication.translate("serverPageWidget", "Proxy Settings:", None))
        self.proxyUserNameLabel.setText(QtGui.QApplication.translate("serverPageWidget", "Login:", None))
        self.proxyPasswordLabel.setText(QtGui.QApplication.translate("serverPageWidget", "Password", None))
        self.proxyServerLabel.setText(QtGui.QApplication.translate("serverPageWidget", "Proxy Server:", None))
        self.environmentsGroupBox.setTitle(QtGui.QApplication.translate("serverPageWidget", "Tactic Environments (Only for TACTIC Team):", None))
        self.tacticEnvLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic Data dir:", None))
        self.tacticInstallDirLable.setText(QtGui.QApplication.translate("serverPageWidget", "Tactic Install dir:", None))
        self.addTacticEnv.setText(QtGui.QApplication.translate("serverPageWidget", "Add Tactic environments to system", None))

