# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tactic/ui_my_tasks.ui'
#
# Created: Thu Apr 27 14:15:15 2017
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from thlib.side.Qt import QtWidgets as QtGui
from thlib.side.Qt import QtCore


class Ui_myTasks(object):
    def setupUi(self, myTasks):
        myTasks.setObjectName("myTasks")
        myTasks.resize(561, 220)
        self.verticalLayout_3 = QtGui.QVBoxLayout(myTasks)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(myTasks)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_2 = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.treeWidget_2.setObjectName("treeWidget_2")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_2)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget_2)
        self.comboBox_2 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeWidget_5 = QtGui.QTreeWidget(self.tab)
        self.treeWidget_5.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_5.setObjectName("treeWidget_5")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_5)
        self.treeWidget_5.header().setDefaultSectionSize(80)
        self.horizontalLayout_3.addWidget(self.treeWidget_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeWidget_7 = QtGui.QTreeWidget(self.tab_4)
        self.treeWidget_7.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_7.setObjectName("treeWidget_7")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_7)
        self.treeWidget_7.header().setDefaultSectionSize(80)
        self.horizontalLayout_4.addWidget(self.treeWidget_7)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget_8 = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget_8.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_8.setObjectName("treeWidget_8")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_8)
        self.treeWidget_8.header().setDefaultSectionSize(80)
        self.horizontalLayout_2.addWidget(self.treeWidget_8)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget_9 = QtGui.QTreeWidget(self.tab_3)
        self.treeWidget_9.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_9.setObjectName("treeWidget_9")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_9)
        self.treeWidget_9.header().setDefaultSectionSize(80)
        self.horizontalLayout.addWidget(self.treeWidget_9)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(myTasks)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(myTasks)

    def retranslateUi(self, myTasks):
        myTasks.setWindowTitle(QtGui.QApplication.translate("myTasks", "Form", None))
        self.treeWidget_2.headerItem().setText(0, QtGui.QApplication.translate("myTasks", "Tasks:", None))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, QtGui.QApplication.translate("myTasks", "ALL", None))
        self.treeWidget_2.topLevelItem(1).setText(0, QtGui.QApplication.translate("myTasks", "Props", None))
        self.treeWidget_2.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("myTasks", "PROPS00001", None))
        self.treeWidget_2.topLevelItem(1).child(1).setText(0, QtGui.QApplication.translate("myTasks", "PROPS00002", None))
        self.treeWidget_2.topLevelItem(2).setText(0, QtGui.QApplication.translate("myTasks", "Characters", None))
        self.treeWidget_2.topLevelItem(2).child(0).setText(0, QtGui.QApplication.translate("myTasks", "CHARACTER00001", None))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("myTasks", "Толстый Админ, Admin", None))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("myTasks", "Алексей Кривоспицкий, listy", None))
        self.treeWidget_5.headerItem().setText(0, QtGui.QApplication.translate("myTasks", "Status", None))
        self.treeWidget_5.headerItem().setText(1, QtGui.QApplication.translate("myTasks", "Priority", None))
        self.treeWidget_5.headerItem().setText(2, QtGui.QApplication.translate("myTasks", "End Date", None))
        self.treeWidget_5.headerItem().setText(3, QtGui.QApplication.translate("myTasks", "Start Date", None))
        self.treeWidget_5.headerItem().setText(4, QtGui.QApplication.translate("myTasks", "Process", None))
        self.treeWidget_5.headerItem().setText(5, QtGui.QApplication.translate("myTasks", "Context", None))
        self.treeWidget_5.headerItem().setText(6, QtGui.QApplication.translate("myTasks", "Supervisor", None))
        self.treeWidget_5.headerItem().setText(7, QtGui.QApplication.translate("myTasks", "Item", None))
        __sortingEnabled = self.treeWidget_5.isSortingEnabled()
        self.treeWidget_5.setSortingEnabled(False)
        self.treeWidget_5.topLevelItem(0).setText(0, QtGui.QApplication.translate("myTasks", "Complete", None))
        self.treeWidget_5.topLevelItem(0).setText(1, QtGui.QApplication.translate("myTasks", "5 - Critical", None))
        self.treeWidget_5.topLevelItem(0).setText(2, QtGui.QApplication.translate("myTasks", "2016-01-28 12:59:07", None))
        self.treeWidget_5.topLevelItem(0).setText(3, QtGui.QApplication.translate("myTasks", "2016-01-25 12:59:07", None))
        self.treeWidget_5.topLevelItem(0).setText(4, QtGui.QApplication.translate("myTasks", "Modeling", None))
        self.treeWidget_5.topLevelItem(0).setText(5, QtGui.QApplication.translate("myTasks", "Modeling/001", None))
        self.treeWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("myTasks", "All", None))
        self.treeWidget_7.headerItem().setText(0, QtGui.QApplication.translate("myTasks", "Priority", None))
        self.treeWidget_7.headerItem().setText(1, QtGui.QApplication.translate("myTasks", "End Date", None))
        self.treeWidget_7.headerItem().setText(2, QtGui.QApplication.translate("myTasks", "Start Date", None))
        self.treeWidget_7.headerItem().setText(3, QtGui.QApplication.translate("myTasks", "Process", None))
        self.treeWidget_7.headerItem().setText(4, QtGui.QApplication.translate("myTasks", "Context", None))
        self.treeWidget_7.headerItem().setText(5, QtGui.QApplication.translate("myTasks", "Supervisor", None))
        __sortingEnabled = self.treeWidget_7.isSortingEnabled()
        self.treeWidget_7.setSortingEnabled(False)
        self.treeWidget_7.topLevelItem(0).setText(0, QtGui.QApplication.translate("myTasks", "5 - Critical", None))
        self.treeWidget_7.topLevelItem(0).setText(1, QtGui.QApplication.translate("myTasks", "2016-01-28 12:59:07", None))
        self.treeWidget_7.topLevelItem(0).setText(2, QtGui.QApplication.translate("myTasks", "2016-01-25 12:59:07", None))
        self.treeWidget_7.topLevelItem(0).setText(3, QtGui.QApplication.translate("myTasks", "Modeling", None))
        self.treeWidget_7.topLevelItem(0).setText(4, QtGui.QApplication.translate("myTasks", "Modeling/001", None))
        self.treeWidget_7.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("myTasks", "Pending", None))
        self.treeWidget_8.headerItem().setText(0, QtGui.QApplication.translate("myTasks", "Priority", None))
        self.treeWidget_8.headerItem().setText(1, QtGui.QApplication.translate("myTasks", "End Date", None))
        self.treeWidget_8.headerItem().setText(2, QtGui.QApplication.translate("myTasks", "Start Date", None))
        self.treeWidget_8.headerItem().setText(3, QtGui.QApplication.translate("myTasks", "Process", None))
        self.treeWidget_8.headerItem().setText(4, QtGui.QApplication.translate("myTasks", "Context", None))
        self.treeWidget_8.headerItem().setText(5, QtGui.QApplication.translate("myTasks", "Supervisor", None))
        __sortingEnabled = self.treeWidget_8.isSortingEnabled()
        self.treeWidget_8.setSortingEnabled(False)
        self.treeWidget_8.topLevelItem(0).setText(0, QtGui.QApplication.translate("myTasks", "5 - Critical", None))
        self.treeWidget_8.topLevelItem(0).setText(1, QtGui.QApplication.translate("myTasks", "2016-01-28 12:59:07", None))
        self.treeWidget_8.topLevelItem(0).setText(2, QtGui.QApplication.translate("myTasks", "2016-01-25 12:59:07", None))
        self.treeWidget_8.topLevelItem(0).setText(3, QtGui.QApplication.translate("myTasks", "Modeling", None))
        self.treeWidget_8.topLevelItem(0).setText(4, QtGui.QApplication.translate("myTasks", "Modeling/001", None))
        self.treeWidget_8.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("myTasks", "In Progress", None))
        self.treeWidget_9.headerItem().setText(0, QtGui.QApplication.translate("myTasks", "Priority", None))
        self.treeWidget_9.headerItem().setText(1, QtGui.QApplication.translate("myTasks", "End Date", None))
        self.treeWidget_9.headerItem().setText(2, QtGui.QApplication.translate("myTasks", "Start Date", None))
        self.treeWidget_9.headerItem().setText(3, QtGui.QApplication.translate("myTasks", "Process", None))
        self.treeWidget_9.headerItem().setText(4, QtGui.QApplication.translate("myTasks", "Context", None))
        self.treeWidget_9.headerItem().setText(5, QtGui.QApplication.translate("myTasks", "Supervisor", None))
        __sortingEnabled = self.treeWidget_9.isSortingEnabled()
        self.treeWidget_9.setSortingEnabled(False)
        self.treeWidget_9.topLevelItem(0).setText(0, QtGui.QApplication.translate("myTasks", "5 - Critical", None))
        self.treeWidget_9.topLevelItem(0).setText(1, QtGui.QApplication.translate("myTasks", "2016-01-28 12:59:07", None))
        self.treeWidget_9.topLevelItem(0).setText(2, QtGui.QApplication.translate("myTasks", "2016-01-25 12:59:07", None))
        self.treeWidget_9.topLevelItem(0).setText(3, QtGui.QApplication.translate("myTasks", "Modeling", None))
        self.treeWidget_9.topLevelItem(0).setText(4, QtGui.QApplication.translate("myTasks", "Modeling/001", None))
        self.treeWidget_9.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("myTasks", "Complete", None))

