# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks\ui_subscriptions.ui'
#
# Created: Mon Apr 22 18:34:43 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_myNotifications(object):
    def setupUi(self, myNotifications):
        myNotifications.setObjectName("myNotifications")
        myNotifications.resize(822, 780)
        self.gridLayout = QtGui.QGridLayout(myNotifications)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(myNotifications)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.verticalLayout.addWidget(self.treeWidget)
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setEditable(True)
        self.comboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.treeWidget_5 = QtGui.QTreeWidget(self.tab)
        self.treeWidget_5.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_5.setObjectName("treeWidget_5")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_5)
        self.treeWidget_5.header().setDefaultSectionSize(80)
        self.horizontalLayout_3.addWidget(self.treeWidget_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeWidget_6 = QtGui.QTreeWidget(self.tab_4)
        self.treeWidget_6.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_6.setObjectName("treeWidget_6")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_6)
        self.treeWidget_6.header().setDefaultSectionSize(80)
        self.horizontalLayout_4.addWidget(self.treeWidget_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget_4 = QtGui.QTreeWidget(self.tab_2)
        self.treeWidget_4.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_4.setObjectName("treeWidget_4")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_4)
        self.treeWidget_4.header().setDefaultSectionSize(80)
        self.horizontalLayout_2.addWidget(self.treeWidget_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget_3 = QtGui.QTreeWidget(self.tab_3)
        self.treeWidget_3.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.treeWidget_3.setObjectName("treeWidget_3")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_3)
        self.treeWidget_3.header().setDefaultSectionSize(80)
        self.horizontalLayout.addWidget(self.treeWidget_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(myNotifications)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(myNotifications)

    def retranslateUi(self, myNotifications):
        myNotifications.setWindowTitle(QtGui.QApplication.translate("myNotifications", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("myNotifications", "Subscriptions:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, QtGui.QApplication.translate("myNotifications", "Guppie", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).setText(0, QtGui.QApplication.translate("myNotifications", "Complex Testing Phase Four", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).setText(0, QtGui.QApplication.translate("myNotifications", "Props", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, QtGui.QApplication.translate("myNotifications", "FINALAPPA", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.topLevelItem(1).child(0).child(1).setText(0, QtGui.QApplication.translate("myNotifications", "IMAlive", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox.setItemText(0, QtGui.QApplication.translate("myNotifications", "Толстый Админ, Admin", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("myNotifications", "Алексей Кривоспицкий, listy", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.headerItem().setText(0, QtGui.QApplication.translate("myNotifications", "Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.headerItem().setText(1, QtGui.QApplication.translate("myNotifications", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.headerItem().setText(2, QtGui.QApplication.translate("myNotifications", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.headerItem().setText(3, QtGui.QApplication.translate("myNotifications", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.headerItem().setText(4, QtGui.QApplication.translate("myNotifications", "Item", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_5.isSortingEnabled()
        self.treeWidget_5.setSortingEnabled(False)
        self.treeWidget_5.topLevelItem(0).setText(0, QtGui.QApplication.translate("myNotifications", "Can you please bring me the water?", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.topLevelItem(0).setText(1, QtGui.QApplication.translate("myNotifications", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.topLevelItem(0).setText(2, QtGui.QApplication.translate("myNotifications", "2016-01-28 12:59:07", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.topLevelItem(0).setText(3, QtGui.QApplication.translate("myNotifications", "Modeling", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.topLevelItem(0).setText(4, QtGui.QApplication.translate("myNotifications", "Props00001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("myNotifications", "SObjects", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(0, QtGui.QApplication.translate("myNotifications", "Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(1, QtGui.QApplication.translate("myNotifications", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(2, QtGui.QApplication.translate("myNotifications", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(3, QtGui.QApplication.translate("myNotifications", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.headerItem().setText(4, QtGui.QApplication.translate("myNotifications", "Item", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_6.isSortingEnabled()
        self.treeWidget_6.setSortingEnabled(False)
        self.treeWidget_6.topLevelItem(0).setText(0, QtGui.QApplication.translate("myNotifications", "Can you please bring me the water?", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.topLevelItem(0).setText(1, QtGui.QApplication.translate("myNotifications", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.topLevelItem(0).setText(2, QtGui.QApplication.translate("myNotifications", "2016-01-28 12:59:07", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.topLevelItem(0).setText(3, QtGui.QApplication.translate("myNotifications", "Modeling", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.topLevelItem(0).setText(4, QtGui.QApplication.translate("myNotifications", "Props00001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_6.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("myNotifications", "Snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(0, QtGui.QApplication.translate("myNotifications", "Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(1, QtGui.QApplication.translate("myNotifications", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(2, QtGui.QApplication.translate("myNotifications", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(3, QtGui.QApplication.translate("myNotifications", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.headerItem().setText(4, QtGui.QApplication.translate("myNotifications", "Item", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_4.isSortingEnabled()
        self.treeWidget_4.setSortingEnabled(False)
        self.treeWidget_4.topLevelItem(0).setText(0, QtGui.QApplication.translate("myNotifications", "Can you please bring me the water?", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.topLevelItem(0).setText(1, QtGui.QApplication.translate("myNotifications", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.topLevelItem(0).setText(2, QtGui.QApplication.translate("myNotifications", "2016-01-28 12:59:07", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.topLevelItem(0).setText(3, QtGui.QApplication.translate("myNotifications", "Modeling", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.topLevelItem(0).setText(4, QtGui.QApplication.translate("myNotifications", "Props00001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("myNotifications", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.headerItem().setText(0, QtGui.QApplication.translate("myNotifications", "Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.headerItem().setText(1, QtGui.QApplication.translate("myNotifications", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.headerItem().setText(2, QtGui.QApplication.translate("myNotifications", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.headerItem().setText(3, QtGui.QApplication.translate("myNotifications", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.headerItem().setText(4, QtGui.QApplication.translate("myNotifications", "Item", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, QtGui.QApplication.translate("myNotifications", "Can you please bring me the water?", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.topLevelItem(0).setText(1, QtGui.QApplication.translate("myNotifications", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.topLevelItem(0).setText(2, QtGui.QApplication.translate("myNotifications", "2016-01-28 12:59:07", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.topLevelItem(0).setText(3, QtGui.QApplication.translate("myNotifications", "Modeling", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.topLevelItem(0).setText(4, QtGui.QApplication.translate("myNotifications", "Props00001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("myNotifications", "Tasks", None, QtGui.QApplication.UnicodeUTF8))

