# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkin_out/ui_checkin_out_widget.ui'
#
# Created: Fri Jan  6 12:48:17 2017
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_checkInOutWidget(object):
    def setupUi(self, checkInOutWidget):
        checkInOutWidget.setObjectName("checkInOutWidget")
        self.checkinOutVerticalLayout = QtGui.QVBoxLayout(checkInOutWidget)
        self.checkinOutVerticalLayout.setSpacing(0)
        self.checkinOutVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.checkinOutVerticalLayout.setObjectName("checkinOutVerticalLayout")
        self.dropPlateSplitter = QtGui.QSplitter(checkInOutWidget)
        self.dropPlateSplitter.setOrientation(QtCore.Qt.Vertical)
        self.dropPlateSplitter.setObjectName("dropPlateSplitter")
        self.commentsSplitter = QtGui.QSplitter(self.dropPlateSplitter)
        self.commentsSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.commentsSplitter.setObjectName("commentsSplitter")
        self.layoutWidget = QtGui.QWidget(self.commentsSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.searchResultsGridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.searchResultsGridLayout.setSpacing(0)
        self.searchResultsGridLayout.setContentsMargins(0, 0, 0, 0)
        self.searchResultsGridLayout.setObjectName("searchResultsGridLayout")
        self.searchLineEdit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet("QLineEdit {\n"
"    border: 0px;\n"
"    border-radius: 8px;\n"
"    show-decoration-selected: 1;\n"
"    padding: 0px 8px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 64), stop:1 rgba(255, 255, 255, 0));\n"
"    background-position: bottom left;\n"
"    background-image: url(\":/ui_check/gliph/search_16.png\");\n"
"    background-repeat: fixed;\n"
"    selection-background-color: darkgray;\n"
"    padding-left: 15px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: white;\n"
"    background-image: url(\":/ui_check/gliph/searchHover_16.png\");\n"
"}")
        self.searchLineEdit.setFrame(False)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchResultsGridLayout.addWidget(self.searchLineEdit, 0, 0, 1, 1)
        self.gearMenuToolButton = QtGui.QToolButton(self.layoutWidget)
        self.gearMenuToolButton.setMaximumSize(QtCore.QSize(22, 22))
        self.gearMenuToolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.gearMenuToolButton.setAutoRaise(True)
        self.gearMenuToolButton.setArrowType(QtCore.Qt.NoArrow)
        self.gearMenuToolButton.setObjectName("gearMenuToolButton")
        self.searchResultsGridLayout.addWidget(self.gearMenuToolButton, 0, 2, 1, 1)
        self.expandingLayout = QtGui.QVBoxLayout()
        self.expandingLayout.setSpacing(0)
        self.expandingLayout.setObjectName("expandingLayout")
        self.searchResultsGridLayout.addLayout(self.expandingLayout, 0, 1, 1, 1)
        self.searchOptionsSplitter = QtGui.QSplitter(self.layoutWidget)
        self.searchOptionsSplitter.setOrientation(QtCore.Qt.Vertical)
        self.searchOptionsSplitter.setObjectName("searchOptionsSplitter")
        self.searchResultsGridLayout.addWidget(self.searchOptionsSplitter, 1, 0, 1, 5)
        self.searchResultsGridLayout.setColumnStretch(0, 1)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.commentsSplitter)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.snapshoBrowserLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.snapshoBrowserLayout.setSpacing(0)
        self.snapshoBrowserLayout.setContentsMargins(0, 0, 0, 0)
        self.snapshoBrowserLayout.setObjectName("snapshoBrowserLayout")
        self.descriptionSplitter = QtGui.QSplitter(self.verticalLayoutWidget_3)
        self.descriptionSplitter.setOrientation(QtCore.Qt.Vertical)
        self.descriptionSplitter.setObjectName("descriptionSplitter")
        self.snapshotBrowserGroupBox = QtGui.QGroupBox(self.descriptionSplitter)
        self.snapshotBrowserGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.snapshotBrowserGroupBox.setFlat(True)
        self.snapshotBrowserGroupBox.setObjectName("snapshotBrowserGroupBox")
        self.snapshotBrowserLayout = QtGui.QVBoxLayout(self.snapshotBrowserGroupBox)
        self.snapshotBrowserLayout.setSpacing(0)
        self.snapshotBrowserLayout.setContentsMargins(0, 0, 0, 0)
        self.snapshotBrowserLayout.setObjectName("snapshotBrowserLayout")
        self.descriptionGroupBox = QtGui.QGroupBox(self.descriptionSplitter)
        self.descriptionGroupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.descriptionGroupBox.setFlat(True)
        self.descriptionGroupBox.setObjectName("descriptionGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.descriptionGroupBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.editorLayout = QtGui.QVBoxLayout()
        self.editorLayout.setSpacing(0)
        self.editorLayout.setObjectName("editorLayout")
        self.verticalLayout.addLayout(self.editorLayout)
        self.descriptionTextEdit = QtGui.QTextEdit(self.descriptionGroupBox)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.saveDescriprionButton = QtGui.QPushButton(self.descriptionGroupBox)
        self.saveDescriprionButton.setObjectName("saveDescriprionButton")
        self.verticalLayout.addWidget(self.saveDescriprionButton)
        self.verticalLayout.setStretch(1, 1)
        self.snapshoBrowserLayout.addWidget(self.descriptionSplitter)
        self.gridLayoutWidget = QtGui.QWidget(self.dropPlateSplitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.dropPlateLayout = QtGui.QHBoxLayout(self.gridLayoutWidget)
        self.dropPlateLayout.setSpacing(0)
        self.dropPlateLayout.setContentsMargins(0, 0, 0, 0)
        self.dropPlateLayout.setContentsMargins(0, 0, 0, 0)
        self.dropPlateLayout.setObjectName("dropPlateLayout")
        self.checkinOutVerticalLayout.addWidget(self.dropPlateSplitter)
        self.fastControlsHorizontalLayout = QtGui.QHBoxLayout()
        self.fastControlsHorizontalLayout.setSpacing(4)
        self.fastControlsHorizontalLayout.setObjectName("fastControlsHorizontalLayout")
        self.toggleSaveOptionsToolButton = QtGui.QToolButton(checkInOutWidget)
        self.toggleSaveOptionsToolButton.setMinimumSize(QtCore.QSize(0, 22))
        self.toggleSaveOptionsToolButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toggleSaveOptionsToolButton.setAutoRaise(True)
        self.toggleSaveOptionsToolButton.setObjectName("toggleSaveOptionsToolButton")
        self.fastControlsHorizontalLayout.addWidget(self.toggleSaveOptionsToolButton)
        self.savePushButton = QtGui.QToolButton(checkInOutWidget)
        self.savePushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePushButton.sizePolicy().hasHeightForWidth())
        self.savePushButton.setSizePolicy(sizePolicy)
        self.savePushButton.setMinimumSize(QtCore.QSize(75, 22))
        self.savePushButton.setChecked(False)
        self.savePushButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.savePushButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.savePushButton.setAutoRaise(True)
        self.savePushButton.setObjectName("savePushButton")
        self.fastControlsHorizontalLayout.addWidget(self.savePushButton)
        self.toggleOpenOptionsToolButton = QtGui.QToolButton(checkInOutWidget)
        self.toggleOpenOptionsToolButton.setMinimumSize(QtCore.QSize(0, 22))
        self.toggleOpenOptionsToolButton.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toggleOpenOptionsToolButton.setAutoRaise(True)
        self.toggleOpenOptionsToolButton.setObjectName("toggleOpenOptionsToolButton")
        self.fastControlsHorizontalLayout.addWidget(self.toggleOpenOptionsToolButton)
        self.openPushButton = QtGui.QToolButton(checkInOutWidget)
        self.openPushButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openPushButton.sizePolicy().hasHeightForWidth())
        self.openPushButton.setSizePolicy(sizePolicy)
        self.openPushButton.setMinimumSize(QtCore.QSize(75, 22))
        self.openPushButton.setChecked(False)
        self.openPushButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.openPushButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.openPushButton.setAutoRaise(True)
        self.openPushButton.setObjectName("openPushButton")
        self.fastControlsHorizontalLayout.addWidget(self.openPushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.fastControlsHorizontalLayout.addItem(spacerItem)
        self.processLabel = QtGui.QLabel(checkInOutWidget)
        self.processLabel.setObjectName("processLabel")
        self.fastControlsHorizontalLayout.addWidget(self.processLabel)
        self.processComboBox = QtGui.QComboBox(checkInOutWidget)
        self.processComboBox.setObjectName("processComboBox")
        self.fastControlsHorizontalLayout.addWidget(self.processComboBox)
        self.contextLabel = QtGui.QLabel(checkInOutWidget)
        self.contextLabel.setTextFormat(QtCore.Qt.PlainText)
        self.contextLabel.setObjectName("contextLabel")
        self.fastControlsHorizontalLayout.addWidget(self.contextLabel)
        self.contextComboBox = QtGui.QComboBox(checkInOutWidget)
        self.contextComboBox.setEditable(True)
        self.contextComboBox.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.contextComboBox.setObjectName("contextComboBox")
        self.fastControlsHorizontalLayout.addWidget(self.contextComboBox)
        self.fastControlsHorizontalLayout.setStretch(4, 1)
        self.fastControlsHorizontalLayout.setStretch(6, 1)
        self.fastControlsHorizontalLayout.setStretch(8, 1)
        self.checkinOutVerticalLayout.addLayout(self.fastControlsHorizontalLayout)
        self.checkinOutVerticalLayout.setStretch(0, 1)

        self.retranslateUi(checkInOutWidget)
        QtCore.QMetaObject.connectSlotsByName(checkInOutWidget)
        checkInOutWidget.setTabOrder(self.searchLineEdit, self.descriptionTextEdit)

    def retranslateUi(self, checkInOutWidget):
        self.snapshotBrowserGroupBox.setTitle(QtGui.QApplication.translate("checkInOutWidget", "Snaphsot browser:", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionGroupBox.setTitle(QtGui.QApplication.translate("checkInOutWidget", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDescriprionButton.setText(QtGui.QApplication.translate("checkInOutWidget", "Save description", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setText(QtGui.QApplication.translate("checkInOutWidget", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.openPushButton.setText(QtGui.QApplication.translate("checkInOutWidget", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.processLabel.setText(QtGui.QApplication.translate("checkInOutWidget", "Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.contextLabel.setText(QtGui.QApplication.translate("checkInOutWidget", "Context:", None, QtGui.QApplication.UnicodeUTF8))

import lib.ui.resources_rc
