# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browser/ui_sobject_info.ui'
#
# Created: Thu Apr 27 14:15:17 2017
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from lib.side.Qt import QtWidgets as QtGui
from lib.side.Qt import QtCore

class Ui_sobjectInfo(object):
    def setupUi(self, sobjectInfo):
        sobjectInfo.setObjectName("sobjectInfo")
        sobjectInfo.resize(800, 600)
        self.centralwidget = QtGui.QWidget(sobjectInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.commentLabel_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentLabel_3.sizePolicy().hasHeightForWidth())
        self.commentLabel_3.setSizePolicy(sizePolicy)
        self.commentLabel_3.setMinimumSize(QtCore.QSize(0, 25))
        self.commentLabel_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.commentLabel_3.setTextFormat(QtCore.Qt.PlainText)
        self.commentLabel_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.commentLabel_3.setWordWrap(True)
        self.commentLabel_3.setMargin(0)
        self.commentLabel_3.setIndent(11)
        self.commentLabel_3.setObjectName("commentLabel_3")
        self.gridLayout.addWidget(self.commentLabel_3, 1, 1, 1, 1)
        self.fileNameLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLabel.sizePolicy().hasHeightForWidth())
        self.fileNameLabel.setSizePolicy(sizePolicy)
        self.fileNameLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.fileNameLabel.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(128, 128, 128, 175), stop:1 rgba(64, 64,64, 0));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(64, 64, 64, 175), stop:1 rgba(255, 255,255, 0));\n"
"    padding: 0px;\n"
"}")
        self.fileNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.fileNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fileNameLabel.setMargin(2)
        self.fileNameLabel.setIndent(15)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.gridLayout.addWidget(self.fileNameLabel, 0, 0, 1, 3)
        self.commentLabel_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentLabel_4.sizePolicy().hasHeightForWidth())
        self.commentLabel_4.setSizePolicy(sizePolicy)
        self.commentLabel_4.setMinimumSize(QtCore.QSize(0, 25))
        self.commentLabel_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.commentLabel_4.setTextFormat(QtCore.Qt.PlainText)
        self.commentLabel_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.commentLabel_4.setWordWrap(True)
        self.commentLabel_4.setMargin(0)
        self.commentLabel_4.setIndent(11)
        self.commentLabel_4.setObjectName("commentLabel_4")
        self.gridLayout.addWidget(self.commentLabel_4, 2, 1, 1, 1)
        self.commentLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentLabel.sizePolicy().hasHeightForWidth())
        self.commentLabel.setSizePolicy(sizePolicy)
        self.commentLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.commentLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.commentLabel.setTextFormat(QtCore.Qt.PlainText)
        self.commentLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.commentLabel.setWordWrap(True)
        self.commentLabel.setMargin(0)
        self.commentLabel.setIndent(11)
        self.commentLabel.setObjectName("commentLabel")
        self.gridLayout.addWidget(self.commentLabel, 1, 2, 1, 1)
        self.keywordsLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordsLabel.sizePolicy().hasHeightForWidth())
        self.keywordsLabel.setSizePolicy(sizePolicy)
        self.keywordsLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.keywordsLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.keywordsLabel.setTextFormat(QtCore.Qt.PlainText)
        self.keywordsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.keywordsLabel.setWordWrap(True)
        self.keywordsLabel.setMargin(0)
        self.keywordsLabel.setIndent(11)
        self.keywordsLabel.setObjectName("keywordsLabel")
        self.gridLayout.addWidget(self.keywordsLabel, 2, 2, 1, 1)
        self.commentLabel_5 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commentLabel_5.sizePolicy().hasHeightForWidth())
        self.commentLabel_5.setSizePolicy(sizePolicy)
        self.commentLabel_5.setMinimumSize(QtCore.QSize(0, 25))
        self.commentLabel_5.setTextFormat(QtCore.Qt.PlainText)
        self.commentLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.commentLabel_5.setWordWrap(True)
        self.commentLabel_5.setMargin(2)
        self.commentLabel_5.setObjectName("commentLabel_5")
        self.gridLayout.addWidget(self.commentLabel_5, 0, 3, 1, 1)
        self.checkOutToolButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkOutToolButton.sizePolicy().hasHeightForWidth())
        self.checkOutToolButton.setSizePolicy(sizePolicy)
        self.checkOutToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.checkOutToolButton.setAutoRaise(True)
        self.checkOutToolButton.setObjectName("checkOutToolButton")
        self.gridLayout.addWidget(self.checkOutToolButton, 1, 3, 1, 1)
        self.checkInToolButton = QtGui.QToolButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkInToolButton.sizePolicy().hasHeightForWidth())
        self.checkInToolButton.setSizePolicy(sizePolicy)
        self.checkInToolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.checkInToolButton.setAutoRaise(True)
        self.checkInToolButton.setObjectName("checkInToolButton")
        self.gridLayout.addWidget(self.checkInToolButton, 2, 3, 1, 1)
        self.gridLayout.setColumnMinimumWidth(3, 150)
        self.gridLayout.setRowMinimumHeight(0, 100)
        self.gridLayout.setRowMinimumHeight(1, 25)
        self.gridLayout.setRowMinimumHeight(2, 25)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tasksTab = QtGui.QWidget()
        self.tasksTab.setObjectName("tasksTab")
        self.tasksLayout = QtGui.QVBoxLayout(self.tasksTab)
        self.tasksLayout.setSpacing(0)
        self.tasksLayout.setContentsMargins(0, 0, 0, 4)
        self.tasksLayout.setObjectName("tasksLayout")
        self.tabWidget.addTab(self.tasksTab, "")
        self.notesTab = QtGui.QWidget()
        self.notesTab.setObjectName("notesTab")
        self.notesLayout = QtGui.QVBoxLayout(self.notesTab)
        self.notesLayout.setSpacing(0)
        self.notesLayout.setContentsMargins(0, 0, 0, 4)
        self.notesLayout.setObjectName("notesLayout")
        self.tabWidget.addTab(self.notesTab, "")
        self.editTab = QtGui.QWidget()
        self.editTab.setObjectName("editTab")
        self.editLayout = QtGui.QVBoxLayout(self.editTab)
        self.editLayout.setSpacing(0)
        self.editLayout.setContentsMargins(0, 0, 0, 4)
        self.editLayout.setObjectName("editLayout")
        self.tabWidget.addTab(self.editTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        sobjectInfo.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(sobjectInfo)
        self.statusbar.setObjectName("statusbar")
        sobjectInfo.setStatusBar(self.statusbar)

        self.retranslateUi(sobjectInfo)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(sobjectInfo)

    def retranslateUi(self, sobjectInfo):
        sobjectInfo.setWindowTitle(QtGui.QApplication.translate("sobjectInfo", "MainWindow", None))
        self.commentLabel_3.setText(QtGui.QApplication.translate("sobjectInfo", "Description:", None))
        self.fileNameLabel.setText(QtGui.QApplication.translate("sobjectInfo", "<html><head/><body><p><span style=\" font-size:16pt;\">Sets: Zal</span></p><p><span style=\" font-size:12pt;\">Code: (SETS00001)</span></p><p align=\"right\"><span style=\" font-size:10pt;\">6 tasks / 144 notes / 45 snapshots</span></p></body></html>", None))
        self.commentLabel_4.setText(QtGui.QApplication.translate("sobjectInfo", "Keywords:", None))
        self.commentLabel.setText(QtGui.QApplication.translate("sobjectInfo", "Big zala, good for gi tests", None))
        self.keywordsLabel.setText(QtGui.QApplication.translate("sobjectInfo", "gi, tests, zal, big, good", None))
        self.commentLabel_5.setText(QtGui.QApplication.translate("sobjectInfo", "PIC", None))
        self.checkOutToolButton.setText(QtGui.QApplication.translate("sobjectInfo", "Checkout Shapshot", None))
        self.checkInToolButton.setText(QtGui.QApplication.translate("sobjectInfo", "Checkin Shapshot", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tasksTab), QtGui.QApplication.translate("sobjectInfo", "Tasks", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notesTab), QtGui.QApplication.translate("sobjectInfo", "Notes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editTab), QtGui.QApplication.translate("sobjectInfo", "Edit", None))

