import PySide.QtGui as QtGui


def dark_style(widget):
    """
    Set default style for given QT widget.
    :widget - Target QT widget.
    """
    palette = widget.style().standardPalette()
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Window, QtGui.QColor(68, 68, 68))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, QtGui.QColor(74, 74, 74))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Text, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Button, QtGui.QColor(100, 100, 100))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.WindowText, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Base, QtGui.QColor(42, 42, 42))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.BrightText, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Light, QtGui.QColor(100, 100, 100))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Midlight, QtGui.QColor(70, 70, 70))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Dark, QtGui.QColor(42, 42, 42))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Mid, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Shadow, QtGui.QColor(0, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Highlight, QtGui.QColor(255, 180, 0, 51))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.Link, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Active, QtGui.QPalette.NoRole, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Window, QtGui.QColor(68, 68, 68))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, QtGui.QColor(74, 74, 74))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Text, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Button, QtGui.QColor(100, 100, 100))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, QtGui.QColor(200, 200, 200))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Base, QtGui.QColor(42, 42, 42))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Light, QtGui.QColor(100, 100, 100))
    palette.setColor(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, QtGui.QColor(255, 180, 0, 51))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Button, QtGui.QColor(80, 80, 80))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, QtGui.QColor(10, 10, 10, 10))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, QtGui.QColor(150, 150, 150))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Window, QtGui.QColor(30, 30, 30))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Text, QtGui.QColor(105, 105, 105))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, QtGui.QColor(105, 105, 105))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Base, QtGui.QColor(68, 68, 68))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Light, QtGui.QColor(68, 68, 68))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, QtGui.QColor(0, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.Link, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, QtGui.QColor(255, 0, 0))
    palette.setColor(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, QtGui.QColor(255, 0, 0))
    widget.setPalette(palette)
